<a href="https://colab.research.google.com/github/jonafel/Tugas-Sentiment-Analysis/blob/main/tugas_akhir_sentimen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##TUGAS AKHIR SENTIMEN ANALISIS JONATHAN FELIX

Melalui Collabs ini saya mencoba menganalisa sentimen komentar yang ada di akun Instagram [Indozone.ID](https://www.instagram.com/p/DEmxFKTzfqm/)

Tapi sebelum cek langsung ke komentar dari Indozone, ayo kita train data sementara cyberbullying. Kita juga harus menyiapkan semua Library yang akan dibutuhkan

In [54]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 3.6 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [2]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.67.1)

In [55]:
import pandas as pd
import nltk
import re
import string
from collections import Counter
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

nltk.download('popular')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

## IMPORT DATA TRAINING & TEXT CLEANING

[dataset CyberBullying](https://drive.google.com/file/d/10mhzsF0lWdc4rqqowsb50K9ZZ_nOwzA8/view?usp=drive_link)

In [106]:
data = pd.read_csv('komentar_instagram_cyberbullying.csv')
data

      Id Sentiment                             Instagram Comment Text
0      1  negative   <USERNAME> TOLOL!! Gak ada hubungan nya kegug...
1      2  negative  Geblek lo tata...cowo bgt dibela2in balikan......
2      3  negative  Kmrn termewek2 skr lengket lg duhhh kok labil ...
3      4  negative  Intinya kalau kesel dengan ATT nya, gausah ke ...
4      5  negative  hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...
..   ...       ...                                                ...
395  396  positive  Bangga sama suami yg selalu ingat istri disela...
396  397  positive  Apaoun pekerjaannya yg penting halal u tuk men...
397  398  positive  Gojek itu mayoritas pegangguran yang lama gak ...
398  399  positive   <USERNAME> aslinya cantik dan ayu loh mbak kr...
399  400  positive   <USERNAME> suami saya seumuran sama saya mba,...

[400 rows x 3 columns]

In [5]:
def text_cleaning(text:str):
  text_cleaned = text.lower()

  pattern = re.compile(r'@\w+')
  clean_url_text = pattern.sub("", text_cleaned)

  clean_number_text = re.sub(r"[\d]+.[\d]+|[\d]+","", clean_url_text)

  pattern = re.compile(r'\(?https?://[^\s$#]+\)?')
  clean_url_text = pattern.sub("", clean_number_text)


  clean_punct_text = clean_url_text.translate(str.maketrans('','',string.punctuation))

  clean_wspace_text = clean_punct_text.strip()
  clean_wspace_text = clean_wspace_text.replace('\n','')
  clean_wspace_text = re.sub(r"[\s][.,]?[\s]"," ",clean_wspace_text)

  clean_wspace_text = re.sub(r'\b(\w+)\1\b', r'\1', clean_wspace_text)

  return clean_wspace_text

[StopWord Bahasa Indonesia](https://drive.google.com/file/d/1E844kUnMSCguYSQcNZzj62aJjQX1HwVO/view?usp=drive_link)

In [6]:
def load_stopwords(filepath):
      try:
          df_stopword = pd.read_csv('stopwordbahasa.csv', encoding='utf-8')
          stopword_list = df_stopword.iloc[:,0].tolist()
          stopword_set = set(stopword_list)

          return stopword_set
      except FileNotFoundError:
          print(f"File not found: {filepath}")
          return set()

In [7]:
def stopword_cleaning(text, stopword_set):
        text_words = text.split()
        cleaned_words = [word for word in text_words if word not in stopword_set]
        return ' '.join(cleaned_words)

In [8]:
stopword_sets = load_stopwords('stopwordbahasa.csv')
stopword_sets

{'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut',
 'berikutnya',
 'berjumlah',
 'berkali-kali',
 'berkata',
 'berkehendak',
 'berkeinginan',
 'berkenaan',
 'berlainan',
 'berlalu',
 'berlangsung',
 'berlebihan',
 'bermacam',
 'bermacam-macam',
 'bermaksud',
 'bermula',
 'bersama',
 'bersama-sama',
 'bersiap',
 'bersiap-siap',
 'bertanya',
 'bertanya-tanya',
 'berturut',
 'berturut-turut',
 'bertutur',
 'berujar',
 'berupa',
 'besar',
 'betul',
 'betulkah',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'bulan',
 'bung',
 'cara',
 'caranya',
 'cukup',
 'cukupkah',
 'cukuplah',
 'cuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'datang',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'dengan',
 'depan',
 'di',
 'dia',
 'diakhiri',
 'diakhirinya',
 'dialah',
 'diantara',
 'diantaranya',
 'diberi',
 'diberikan',
 'diberikannya',
 'dibuat',
 'dibuatnya',
 'didapat',
 'didatangkan',
 'digunakan',
 'diibaratkan',
 'diibaratkannya',
 'diingat',
 'diingatkan',
 'diinginkan',
 'dijawab',
 'dijelaskan',
 'dijelaskannya',
 'dikarenakan',
 'dikatakan',
 'dikatakannya',
 'dikerjakan',
 'diketahui',
 'diketahuinya',
 'dikira',
 'dilakukan',
 'dilalui',
 'dilihat',
 'dimaksud',
 'dimaksudkan',
 'dimaksudkannya',
 'dimaksudnya',
 'diminta',
 'dimintai',
 'dimisalkan',
 'dimulai',
 'dimulailah',
 'dimulainya',
 'dimungkinkan',
 'dini',
 'dipastikan',
 'diperbuat',
 'diperbuatnya',
 'dipergunakan',
 'diperkirakan',
 'diperlihatkan',
 'diperlukan',
 'diperlukannya',
 'dipersoalkan',
 'dipertanyakan',
 'dipunyai',
 'diri',
 'dirinya',
 'disampaikan',
 'disebut',
 'disebutkan',
 'disebutkannya',
 'disini',
 'disinilah',
 'ditambahkan',
 'ditandaskan',
 'ditanya',
 'ditanyai',
 'ditanyakan',
 'ditegaskan',
 'ditujukan',
 'ditunjuk',
 'ditunjuki',
 'ditunjukkan',
 'ditunjukkannya',
 'ditunjuknya',
 'dituturkan',
 'dituturkannya',
 'diucapkan',
 'diucapkannya',
 'diungkapkan',
 'dong',
 'dua',
 'dulu',
 'empat',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'guna',
 'gunakan',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'hari',
 'harus',
 'haruslah',
 'harusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'ia',
 'ialah',
 'ibarat',
 'ibaratkan',
 'ibaratnya',
 'ibu',
 'ikut',
 'ingat',
 'ingat-ingat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jadi',
 'jadilah',
 'jadinya',
 'jangan',
 'jangankan',
 'janganlah',
 'jauh',
 'jawab',
 'jawaban',
 'jawabnya',
 'jelas',
 'jelaskan',
 'jelaslah',
 'jelasnya',
 'jika',
 'jikalau',
 'juga',
 'jumlah',
 'jumlahnya',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'karena',
 'karenanya',
 'kasus',
 'kata',
 'katakan',
 'katakanlah',
 'katanya',
 'ke',
 'keadaan',
 'kebetulan',
 'kecil',
 'kedua',
 'keduanya',
 'keinginan',
 'kelamaan',
 'kelihatan',
 'kelihatannya',
 'kelima',
 'keluar',
 'kembali',
 'kemudian',
 'kemungkinan',
 'kemungkinannya',
 'kenapa',
 'kepada',
 'kepadanya',
 'kesampaian',
 'keseluruhan',
 'keseluruhannya',
 'keterlaluan',
 'ketika',
 'khususnya',
 'kini',
 'kinilah',
 'kira',
 'kira-kira',
 'kiranya',
 'kita',
 'kitalah',
 'kok',
 'kurang',
 'lagi',
 'lagian',
 'lah',
 'lain',
 'lainnya',
 'lalu',
 'lama',
 'lamanya',
 'lanjut',
 'lanjutnya',
 'lebih',
 'lewat',
 'lima',
 'luar',
 'macam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masa',
 'masalah',
 'masalahnya',
 'masih',
 'masihkah',
 'masing',
 'masing-masing',
 'mau',
 'maupun',
 'melainkan',
 'melakukan',
 'melalui',
 'melihat',
 'melihatnya',
 'memang',
 'memastikan',
 'memberi',
 'memberikan',
 'membuat',
 'memerlukan',
 'memihak',
 'meminta',
 'memintakan',
 'memisalkan',
 'memperbuat',
 'mempergunakan',
 'memperkirakan',
 'memperlihatkan',
 'mempersiapkan',
 'mempersoalkan',
 'mempertanyakan',
 'mempunyai',
 'memulai',
 'memungkinkan',
 'menaiki',
 'menambahkan',
 'menandaskan',
 'menanti',
 'menanti-nanti',
 'menantikan',
 'menanya',
 'menanyai',
 'menanyakan',
 'mendapat',
 'mendapatkan',
 'mendatang',
 'mendatangi',
 'mendatangkan',
 'menegaskan',
 'mengakhiri',
 'mengapa',
 'mengatakan',
 'mengatakannya',
 'mengenai',
 'mengerjakan',
 'mengetahui',
 'menggunakan',
 'menghendaki',
 'mengibaratkan',
 'mengibaratkannya',
 'mengingat',
 'mengingatkan',
 'menginginkan',
 'mengira',
 'mengucapkan',
 'mengucapkannya',
 'mengungkapkan',
 'menjadi',
 'menjawab',
 'menjelaskan',
 'menuju',
 'menunjuk',
 'menunjuki',
 'menunjukkan',
 'menunjuknya',
 'menurut',
 'menuturkan',
 'menyampaikan',
 'menyangkut',
 'menyatakan',
 'menyebutkan',
 'menyeluruh',
 'menyiapkan',
 'merasa',
 'mereka',
 'merekalah',
 'merupakan',
 'meski',
 'meskipun',
 'meyakini',
 'meyakinkan',
 'minta',
 'mirip',
 'misal',
 'misalkan',
 'misalnya',
 'mula',
 'mulai',
 'mulailah',
 'mulanya',
 'mungkin',
 'mungkinkah',
 'nah',
 'naik',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'nyatanya',
 'oleh',
 'olehnya',
 'pada',
 'padahal',
 'padanya',
 'pak',
 'paling',
 'panjang',
 'pantas',
 'para',
 'pasti',
 'pastilah',
 'penting',
 'pentingnya',
 'per',
 'percuma',
 'perlu',
 'perlukah',
 'perlunya',
 'pernah',
 'persoalan',
 'pertama',
 'pertama-tama',
 'pertanyaan',
 'pertanyakan',
 'pihak',
 'pihaknya',
 'pukul',
 'pula',
 'pun',
 'punya',
 'rasa',
 'rasanya',
 'rata',
 'rupanya',
 'saat',
 'saatnya',
 'saja',
 'sajalah',
 'saling',
 'sama',
 'sama-sama',
 'sambil',
 'sampai',
 'sampai-sampai',
 'sampaikan',
 'sana',
 'sangat',
 'sangatlah',
 'satu',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebagai',
 'sebagaimana',
 'sebagainya',
 'sebagian',
 'sebaik',
 'sebaik-baiknya',
 'sebaiknya',
 'sebaliknya',
 'sebanyak',
 'sebegini',
 'sebegitu',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'seberapa',
 'sebesar',
 'sebetulnya',
 'sebisanya',
 'sebuah',
 'sebut',
 'sebutlah',
 'sebutnya',
 'secara',
 'secukupnya',
 'sedang',
 'sedangkan',
 'sedemikian',
 'sedikit',
 'sedikitnya',
 'seenaknya',
 'segala',
 'segalanya',
 'segera',
 'seharusnya',
 'sehingga',
 'seingat',
 'sejak',
 'sejauh',
 'sejenak',
 'sejumlah',
 'sekadar',
 'sekadarnya',
 'sekali',
 'sekali-kali',
 'sekalian',
 'sekaligus',
 'sekalipun',
 'sekarang',
 'sekecil',
 'seketika',
 'sekiranya',
 'sekitar',
 'sekitarnya',
 'sekurang-kurangnya',
 'sekurangnya',
 'sela',
 'selain',
 'selaku',
 'selalu',
 'selama',
 'selama-lamanya',
 'selamanya',
 'selanjutnya',
 'seluruh',
 'seluruhnya',
 'semacam',
 'semakin',
 'semampu',
 'semampunya',
 'semasa',
 'semasih',
 'semata',
 'semata-mata',
 'semaunya',
 'sementara',
 'semisal',
 'semisalnya',
 'sempat',
 'semua',
 'semuanya',
 'semula',
 'sendiri',
 'sendirian',
 'sendirinya',
 'seolah',
 'seolah-olah',
 'seorang',
 'sepanjang',
 'sepantasnya',
 'sepantasnyalah',
 'seperlunya',
 'seperti',
 'sepertinya',
 'sepihak',
 'sering',
 'seringnya',
 'serta',
 'serupa',
 'sesaat',
 'sesama',
 'sesampai',
 'sesegera',
 'sesekali',
 'seseorang',
 'sesuatu',
 'sesuatunya',
 'sesudah',
 'sesudahnya',
 'setelah',
 'setempat',
 'setengah',
 'seterusnya',
 'setiap',
 'setiba',
 'setibanya',
 'setidak-tidaknya',
 'setidaknya',
 'setinggi',
 'seusai',
 'sewaktu',
 'siap',
 'siapa',
 'siapakah',
 'siapapun',
 'sini',
 'sinilah',
 'soal',
 'soalnya',
 'suatu',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tahu',
 'tahun',
 'tak',
 'tambah',
 'tambahnya',
 'tampak',
 'tampaknya',
 'tandas',
 'tandasnya',
 'tanpa',
 'tanya',
 'tanyakan',
 'tanyanya',
 'tapi',
 'tegas',
 'tegasnya',
 'telah',
 'tempat',
 'tengah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tepat',
 'terakhir',
 'terasa',
 'terbanyak',
 'terdahulu',
 'terdapat',
 'terdiri',
 'terhadap',
 'terhadapnya',
 'teringat',
 'teringat-ingat',
 'terjadi',
 'terjadilah',
 'terjadinya',
 'terkira',
 'terlalu',
 'terlebih',
 'terlihat',
 'termasuk',
 'ternyata',
 'tersampaikan',
 'tersebut',
 'tersebutlah',
 'tertentu',
 'tertuju',
 'terus',
 'terutama',
 'tetap',
 'tetapi',
 'tiap',
 'tiba',
 'tiba-tiba',
 'tidak',
 'tidakkah',
 'tidaklah',
 'tiga',
 'tinggi',
 'toh',
 'tunjuk',
 'turut',
 'tutur',
 'tuturnya',
 'ucap',
 'ucapnya',
 'ujar',
 'ujarnya',
 'umum',
 'umumnya',
 'ungkap',
 'ungkapnya',
 'untuk',
 'usah',
 'usai',
 'waduh',
 'wah',
 'wahai',
 'waktu',
 'waktunya',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakin',
 'yakni',
 'yang'}

Kita bersihkan data dari Kolom Instagram Comment Text

In [107]:
data['text_cleaned'] = data['Instagram Comment Text'].apply(text_cleaning)
data

,Id,Sentiment,Instagram Comment Text,text_cleaned
0,1,negative,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...
1,2,negative,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tatacowo bgt dibelain balikanhadewwn...
2,3,negative,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...
3,4,negative,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...
4,5,negative,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lgsakit jiwaknp harus d...
...,...,...,...,...
395,396,positive,Bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...
396,397,positive,Apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg penting halal u tuk men...
397,398,positive,Gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...
398,399,positive,<USERNAME> aslinya cantik dan ayu loh mbak kr...,username aslinya cantik dan ayu loh mbak krn a...
399,400,positive,"<USERNAME> suami saya seumuran sama saya mba,...",username suami saya seumuran sama saya mba mal...

In [108]:
data['text_non_stopword'] = data['text_cleaned'].apply(stopword_cleaning, stopword_set=stopword_sets)
data

,Id,Sentiment,Instagram Comment Text,text_cleaned,text_non_stopword
0,1,negative,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,username tolol gak ada hubungan nya keguguran ...
1,2,negative,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tatacowo bgt dibelain balikanhadewwn...,geblek lo tatacowo bgt dibelain balikanhadewwn...
2,3,negative,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,kmrn termewek skr lengket lg duhhh labil bgt s...
3,4,negative,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,intinya kesel att nya gausah anaknya kasian pe...
4,5,negative,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lgsakit jiwaknp harus d...,hadewwwww permpuan lgsakit jiwaknp yg jd peran...
...,...,...,...,...,...
395,396,positive,Bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...,bangga suami yg istri disela apapun profesimu ...
396,397,positive,Apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg halal u tuk menafkahi k...
397,398,positive,Gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...,gojek mayoritas pegangguran gak kerja trus put...
398,399,positive,<USERNAME> aslinya cantik dan ayu loh mbak kr...,username aslinya cantik dan ayu loh mbak krn a...,username aslinya cantik ayu loh mbak krn berte...
399,400,positive,"<USERNAME> suami saya seumuran sama saya mba,...",username suami saya seumuran sama saya mba mal...,username suami seumuran mba tuaan alhamdulilla...

Setelah dibersihkan dari tanda baca, huruf besar kecilnya dan Stopword, kita cek kata yang peling sering muncul

In [34]:
from nltk.tokenize import word_tokenize
tokens = data['text_non_stopword'].tolist()

In [27]:
list_of_list = [word_tokenize(sentence) for sentence in tokens]
list_of_token = [word for sentence in list_of_list for word in sentence]

print(list_of_list)
print(list_of_token)

[['username', 'tolol', 'gak', 'ada', 'hubungan', 'nya', 'keguguran', 'dgn', 'pake', 'hijab', 'syari', 'yg', 'lo', 'bilang', 'bayi', 'nya', 'kepanasan', 'didalem', 'gak', 'ada', 'hubungan', 'nya', 'woyyyy', 'otak', 'jempol', 'lo', 'gak', 'singkron', 'sih', 'ya', 'nulis', 'komentar'], ['geblek', 'lo', 'tatacowo', 'bgt', 'dibelain', 'balikanhadewwntar', 'ditinggal', 'lg', 'nyalahin', 'tuh', 'cowopadahal', 'kitenya', 'yg', 'oon'], ['kmrn', 'termewek', 'skr', 'lengket', 'lg', 'duhhh', 'labil', 'bgt', 'sih', 'mbak', 'kya', 'abege', 'ajah', 'ato', 'yg', 'kmrn', 'cari', 'sensasi', 'biar', 'top', 'markotoppp', 'ertong', 'gk', 'berkualitas'], ['intinya', 'kesel', 'att', 'nya', 'gausah', 'anaknya', 'kasian', 'perkembangan', 'psikis', 'anak', 'kedepannya', 'orang', 'bener', 'bener', 'tolol', 'skrg', 'seandainya', 'anak', 'anaknya', 'dikatain', 'orang', 'benci', 'gimana', 'perasaan', 'benci', 'tau', 'batesnya', 'namanya', 'manusia', 'gaakan', 'penyuka', 'ada', 'haters'], ['hadewwwww', 'permpuan', 'lgsakit', 'jiwaknp', 'yg', 'jd', 'peran', 'utama', 'film', 'hantu', 'jeruk', 'purutky', 'khabisan', 'stok', 'artis', 'ja'], ['pantesan', 'tinggalin', 'laki', 'ya', 'lakinya', 'mikir', 'kali', 'perempuannya', 'kayagni', 'ngurus', 'aja', 'gak', 'becus', 'gimana', 'ngurus', 'anak', 'mending', 'anak', 'bapake', 'nya', 'aja', 'bener', 'didiknya'], ['kebiasaan', 'balajaer', 'nyampah', 'd', 'ig', 'artissuka', 'yg', 'ig', 'bikin', 'caption', 'apakok', 'balajaer', 'yg', 'heboh', 'asik', 'ceramahin', 'yg', 'igtar', 'd', 'bikinin', 'lagu', 'sm', 'teh', 'melly', 'loh', 'balajaer', 'yg', 'berjudulketika', 'balajaer', 'bersabdademi', 'seonggak', 'koin', 'laknat', 'nyabalajaer', 'ngamuk', 'mengiyakan', 'banget', 'koin', 'laknat', 'nya', 'jd', 'penggoda', 'd', 'rt', 'nya', 'gigiduh', 'elah', 'balajaer', 'smua', 'tau', 'kale', 'kelakuan', 'biduan', 'lo', 'kek', 'apaminus', 'segalanyalagi', 'd', 'bela', 'matianpd', 'sakit', 'jiwa'], ['krn', 'rakyat', 'indonesia', 'bodoh', 'tdk', 'membedakan', 'yg', 'yg', 'buruk', 'sdh', 'tau', 'prilaku', 'buruk', 'tdk', 'tau', 'sopan', 'santun', 'yg', 'dipilih', 'jd', 'panutan', 'mengidolakan', 'yg', 'murahan', 'dr', 'pd', 'yg', 'berkelas', 'ber', 'etika'], ['ayu', 'janda', 'bego', 'pny', 'suami', 'kpn', 'nikah', 'laginya'], ['anyiennnnggg', 'suaranya', 'ancur', 'banget', 'merdu', 'tukang', 'gorengan'], ['syarat', 'sah', 'nikah', 'agama', 'islam', 'cpp', 'cpw', 'saksi', 'wali', 'nikah', 'mas', 'kawinmahar', 'perkara', 'makeup', 'gak', 'manglingi', 'syarat', 'sah', 'pernikahan', 'gak', 'makeup', 'syarat', 'yg', 'terpenuhi', 'pernikahannya', 'sah', 'yak', 'emak', 'emak', 'julids'], ['cewek', 'gatau', 'nih', 'ngerebut', 'pacar', 'org', 'udh', 'abang', 'yg', 'ngedukung', 'sifat', 'jeleknya', 'lg', 'ck'], ['username', 'eh', 'situ', 'kids', 'jaman', 'now', 'ya', 'kebanyakan', 'micin', 'mna', 'yg', 'ngina', 'bego', 'dipelihara'], ['jijik', 'liatnya', 'suer', 'deh', 'minceeee'], ['emang', 'tabu', 'ciuman', 'gitu', 'iya', 'emang', 'yg', 'bikin', 'eneg', 'pencitraan', 'nya', 'yg', 'sok', 'alim', 'sok', 'sok', 'bijak', 'sok', 'sok', 'yg', 'lainya', 'seandainya', 'pencitraan', 'sok', 'alim', 'sok', 'suci', 'serius'], ['yg', 'jd', 'ciuman', 'dpn', 'org', 'bnyk', 'yg', 'sih', 'malu', 'kecuali', 'mgkn', 'lg', 'mabok', 'jd', 'gak', 'ada', 'malu', 'berteman', 'helooow', 'pertemanan', 'tdk', 'melibatkan', 'ciuman', 'bibir', 'coba', 'aja', 'bayangin', 'sanggup', 'gak', 'ciuman', 'bibir', 'ma', 'teman', 'lbh', 'dr', 'teman', 'dasar', 'kelakuan', 'kids', 'jaman', 'now', 'yg', 'emg', 'bego', 'krn', 'kebanyakan', 'micin', 'lho', 'yah'], ['anjing', 'nya', 'ngamukhidup', 'dmana', 'pny', 'musuhudh', 'kliatan', 'mna', 'yg', 'bukanorg', 'ga', 'pny', 'byk', 'musuh'], ['username', 'ahhh', 'jaga', 'ucapan', 'lahh', 'ucapan', 'ngk', 'dijaga', 'dasar', 'munafik', 'dasar', 'betina', 'zaman', 'now', 'ellu', 'kali', 'yangg', 'kelebihan', 'micin', 'loe', 'otak', 'loe', 'selangkangan', 'paham', 'semoga', 'tuhan', 'ampunin', 'kemunafikan', 'loe', 'cun'], ['username', 'yaa', 'ampun', 'upil', 'naruto', 'mencerminkan', 'klo', 'yg', 'pecunpengalaman', 'banget', 'lu', 'yaa', 'kesian', 'gua', 'prihatin', 'mati', 'aj', 'deh', 'lu', 'ngotorin', 'dunia', 'manusia', 'kau'], ['cuman', 'jual', 'goyangan', 'yak', 'suara', 'taik'], ['kasian', 'ih', 'nyari', 'uang', 'sampe', 'segitunya'], ['anjir', 'tontonan', 'yg', 'bermutu'], ['dlu', 'inul', 'goyang', 'ngebor', 'baju', 'ketat', 'dcekal', 'hrs', 'ny', 'ni', 'jg', 'dg', 'sgja', 'goyang', 'da', 'mulu', 'suara', 'ga', 'sbrpa', 'mrsk', 'moral', 'ank', 'muda', 'yg', 'nnton', 'bawaannya', 'nafsu', 'aja'], ['pnyanyi', 'dangdut', 'yg', 'ga', 'berkelas', 'bgini', 'nih', 'bukany', 'nonjolin', 'suara', 'nonjolin', 'da'], ['najis', 'najis', 'udh', 'homo', 'aja', 'org', 'kaya', 'gini', 'musnahkan', 'muka', 'bumi'], ['haduuh', 'orang', 'gak', 'akhlak', 'bangeg', 'perasaan', 'kerjaan', 'berantem', 'mulu', 'musuhnya'], ['s', 'lonte', 'bkn', 'sensasi', 'ngjak', 'ribut', 'org', 'mulu', 'sampah'], ['kayak', 'banci', 'dh', 'nenek', 'pny', 'cu', 'mw', 'operasi', 'mua', 'top', 'ttp', 'aj', 'klo', 'asli', 'ny', 'g', 'cantik', 'dlm'], ['bagus', 'kalo', 'mingkem', 'aja', 'hahaha', 'jahatnya', 'akuuu'], ['oplas', 'dipermak', 'tetep', 'jelek', 'pokoknya', 'mukanya', 'tegang', 'kek', 'banci', 'udah', 'sekian'], ['mending', 'liat', 'dek', 'molen', 'biarpun', 'cowok', 'tp', 'cuantik', 'gak', 'kaya', 'cewe', 'tp', 'kayak', 'bencong', 'wkwkwk'], ['bencong', 'rombengmenjijikangay', 'jg'], ['orang', 'gila', 'pengen', 'hitz', 'cri', 'tenar', 'rela', 'dipenjara', 'cari', 'sensasi', 'settingan', 'beken', 'smpe', 'hina', 'org', 'astagfirullah', 'sekaya', 'sih', 'org', 'kaya', 'mulut', 'nya', 'ky', 'sampahga', 'sekolah', 'ya'], ['cowok', 'anjing', 'cuihhh', 'orang', 'kaya', 'berkoar', 'gua', 'orang', 'ping', 'kaya', 'seduniakarena', 'orang', 'tau', 'klo', 'orang', 'kaya', 'orang', 'kaya', 'malahn', 'berperilaku', 'orang', 'sederhana', 'memamerkan', 'kekayaan', 'dunia', 'akhirat', 'mampus', 'lu', 'harta', 'kagak', 'bawa', 'mati', 'pants', 'buang', 'laut', 'lu', 'orang', 'anehhh'], ['cari', 'sensasi', 'tenar', 'trus', 'banya', 'folowers', 'nya', 'gak', 'gt', 'gt', 'jg', 'kalee', 'darar', 'orang', 'setres', 'ngomong', 'aja', 'belepotan', 'gk', 'gt', 'kamfungan'], ['ngomong', 'aja', 'belepotan', 'gaya', 'lu', 'bencong'], ['orang', 'kebanyakan', 'makan', 'taik', 'ya', 'giniotaknya', 'udah', 'penuh', 'taik', 'jdi', 'gak', 'berfikir', 'positifdari', 'berbicara', 'aja', 'gak', 'bermoraldasar', 'kaum', 'laknat', 'banci', 'anjing', 'kbanyakan', 'burit', 'sih', 'lo', 'jdi', 'stresmanusia', 'ogah', 'jumpa', 'lo', 'anjingcuma', 'anjing', 'yg', 'ketemu', 'lo', 'taik'], ['sikat', 'abiss', 'lahh', 'orng', 'sialan', 'kaya', 'gini', 'pemimpin', 'negara', 'gak', 'hormatin', 'jgn', 'mentang', 'president', 'sembarangin', 'marah', 'gak', 'hina', 'pemimpin', 'harap', 'tindak', 'hukum', 'orng', 'iniö'], ['jijik', 'banget', 'lihat', 'tingkah', 'si', 'upil', 'mudahan', 'secepatnya', 'tidur'], ['edan', 'nih', 'orang', 'udh', 'makan', 'uang', 'rakyat', 'tidur'], ['manusia', 'laknat', 'matinya', 'apain', 'ya'], ['sakit', 'otak', 'hatinya', 'mah', 'udah', 'gak', 'ada', 'nurani', 'urat', 'malunya', 'pajak', 'loh', 'ngegaji', 'orang', 'gila', 'hormat'], ['anak', 'babi', 'bangsat', 'pengen', 'sumpel', 'timah', 'panas', 'congor', 'lu', 'biar', 'modar'], ['pengen', 'sumpel', 'timah', 'panas', 'congor', 'si', 'anak', 'babi', 'pesek', 'buruk', 'rupa'], ['hey', 'anak', 'bangsat', 'babi', 'pesek', 'buruk', 'rupa', 'keritingpengen', 'penggal', 'leher', 'lu', 'sampe', 'putuslumayan', 'makanan', 'buaya'], ['ratu', 'pelakor', 'sejagat', 'raya', 'dimana', 'lonte', 'ya', 'gak', 'malu', 'yg', 'ngerasa', 'lonte', 'tolong', 'malu', 'dikit'], ['mahhhh', 'pertemuan', 'buah', 'ranum', 'buah', 'busuk', 'dah', 'tau', 'yg', 'busuk', 'yg', 'manah', 'mentoknya', 'mah', 'gitu', 'aja', 'kalo', 'pelakor'], ['ah', 'manda', 'mah', 'gatel', 'ga', 'liyat', 'cowo', 'dikit', 'lgsg', 'disosor', 'begok', 'aje', 'yg', 'ama', 'manda', 'kegatelan', 'cewe'], ['si', 'amanda', 'mukanya', 'tante', 'umur', 'tp', 'muka', 'boros', 'banget', 'dasar', 'cabe', 'jujur', 'gua', 'mah', 'kgk', 'suka', 'ama', 'ni', 'haltis'], ['astagah', 'demen', 'ama', 'cewek', 'dekil', 'kumel', 'nagita', 'turun', 'att', 'nagita', 'kaya', 'emas', 'att', 'kaya', 'barlen'], ['alah', 'laki', 'laki', 'jaman', 'skrg', 'sm', 'aja', 'bejat', 'ustad', 'kek', 'kek', 'gila', 'bgt', 'sm', 'perempuan', 'yg', 'istrinya', 'stju', 'bgt', 'sm', 'yg', 'blg', 'ustazah', 'username', 'msuk', 'surga', 'bkan', 'krna', 'poligami', 'msh', 'bnyk', 'yg', 'bs', 'jd', 'akhlak', 'bs', 'masuk', 'surga', 'yaa', 'smoga', 'aja', 'sih', 'perempuan', 'perempuan', 'pelakor', 'diluar', 'sna', 'azab', 'yg', 'gak', 'diampuni', 'hidupnya', 'gk', 'selamat', 'dunia', 'akhirat'], ['gilaaaaa', 'pelakor', 'bnget', 'laki', 'gatal', 'alasan', 'berpoligami', 'woiii', 'mikir', 'pake', 'otak', 'haduh', 'pikir', 'org', 'pintar', 'tau', 'agama', 'buruk', 'allah', 'menguji', 'kesetiaan', 'nafsunya', 'eh', 'kaya', 'gtu', 'menyakiti', 'istri', 'sja', 'menutup', 'pintu', 'rejekimu', 'anak', 'istri', 'kau', 'korbankan', 'sbg', 'seorg', 'imam', 'keluarga', 'gagal', 'mmpertahankan', 'rmh', 'tangganya', 'mencoreng', 'nama', 'nya', 'sndiri', 'smua', 'org', 'suka', 'skrg', 'benci', 'm'], ['biasalah', 'kalo', 'pelakor', 'lbh', 'ancur', 'mukanya', 'istri', 'sah', 'barang', 'bagus', 'cepat', 'laku', 'pelakor', 'jelek', 'nggak', 'laku', 'ngembat', 'laki', 'orang', 'ya', 'udah', 'gatel', 'cocok', 'wes', 'username'], ['ilfil', 'deh', 'sm', 'ni', 'ertong', 'captionig', 'story', 'nya', 'ngomongin', 'org', 'mlu', 'org', 'jd', 'ambigu', 'nilai', 'si', 'a', 'si', 'b', 'si', 'c', 'udah', 'gt', 'kaya', 'zholimi', 'salahinnya', 'lawan', 'jgn', 'ngmg', 'status', 'ah', 'nya', 'dewasa'], ['username', 'pemikiran', 'manusia', 'bodoh', 'eehhh', 'tanteibuomaempo', 'otak', 'lu', 'picik', 'bngt', 'ya', 'jga', 'manusi', 'ada', 'larangan', 'emang', 'dunia', 'orang', 'larang', 'ngungkapin', 'unek', 'stupid', 'human'], ['heran', 'deh', 'yg', 'ngatain', 'si', 'via', 'baperan', 'ya', 'wajar', 'dese', 'baper', 'udin', 'muak', 'orang', 'yg', 'munafik', 'sokan', 'dese', 'kabar', 'yg', 'baperan', 'laki', 'orang', 'ga', 'nyadar', 'tuh', 'pemujanya', 'att', 'gotong', 'royong', 'nasehatin', 'att', 'menggila', 'muja', 'att', 'mojokin', 'viaa', 'dese', 'manusia', 'keles', 'ahh'], ['username', 'yg', 'komen', 'via', 'nyinyir', 'mulu', 'duh', 'kyak', 'gak', 'nyinyirin', 'orang', 'aja', 'parah', 'kalo', 'org', 'sok', 'bener', 'mah', 'gitu', 'pdhal', 'media', 'sosial', 'hak', 'instagram', 'instagram', 'yg', 'nyinyir', 'gak', 'pake', 'ig', 's'], ['username', 'pemikiran', 'manusia', 'bodoh', 'eehhh', 'tanteibuomaempo', 'otak', 'lu', 'picik', 'bngt', 'ya', 'jga', 'manusi', 'ada', 'larangan', 'emang', 'dunia', 'orang', 'larang', 'ngungkapin', 'unek', 'stupid', 'human'], ['username', 'nya', 'ngatain', 'org', 'nyindir', 'netijen', 'goblog', 'banyakan', 'masyako'], ['username', 'didik', 'ortunya', 'nagita', 'bagus', 'heran', 'dg', 'balajaer', 'nagita', 'yah', 'yg', 'dirugikan', 'sm', 'junjunganny', 'knp', 'yg', 'dibenci', 'bodoh', 'bgt', 'asli'], ['username', 'pdhl', 'km', 'kampungan', 'lohpake', 'kerudung', 'mulutnya', 'cuihh'], ['belajaer', 'tuh', 'ya', 'haha', 'bela', 'artis', 'ampe', 'sebegitunya', 'manusah', 'begoh'], ['username', 'iya', 'norak', 'kampyuung', 'coba', 'liat', 'artis', 'adem', 'ayem', 'liat', 'isyana', 'liat', 'agnezmo', 'liat', 'mba', 'liaaat', 'diliat', 'aja', 'coba', 'telaah', 'deh', 'dikasih', 'tau', 'contoh', 'artis', 'better', 'eh', 'jawabannya', 'ya', 'cocok', 'la'], ['username', 'gak', 'sok', 'high', 'class', 'mba', 'liat', 'komenmu', 'artis', 'beda', 'mbak', 'ada', 'yg', 'suka', 'curhat', 'ig', 'ada', 'yg', 'curhat', 'temen', 'ada', 'yg', 'curhat', 'tuhan', 'ngak', 'trus', 'mulut', 'situ', 'maju', 'otaknya', 'mikirnya', 'yg', 'curh'], ['username', 'goblok', 'gak', 'netizen', 'yg', 'kontra', 'sm', 'postingan', 'si', 'via', 'bakajaer', 'kali', 'mbamas', 'ih', 'goblok', 'dipiara', 'lol'], ['sih', 'emg', 'artis', 'ko', 'artis', 'indo', 'ny', 'ngurus', 'prestasi', 'sosmed', 'ny', 'mulu', 'isi', 'nya', 'jd', 'jatoh', 'nya', 'kampungan'], ['username', 'aj', 'kn', 'y', 'mba', 'kaya', 'agnes', 'mo', 'bnyk', 'penghargaan', 'ny', 'tp', 'g', 'kampungan', 'beda', 'am', 'yg'], ['munafik', 'bgt', 'yg', 'ngomong', 'curhat', 'sosmed', 'kampungan', 'gua', 'elu', 'kitu', 'keleusss', 'wkkwkww', 'mending', 'mba', 'via', 'artis', 'cantik', 'bs', 'nyanyi', 'la', 'elu', 'lbh', 'kampungan', 'wkwkwkwkw'], ['usernamewawan', 'zzzzz', 'emng', 'artis', 'ga', 'tmn', 'dikit', 'dikit', 'att', 'hahaha', 'curhat', 'sosmed', 'kampungan'], ['lemes', 'ya', 'mulutnya', 'berani', 'ststus', 'udah', 'gitu', 'tulisannya', 'sengaja', 'biar', 'ga', 'kebaca', 'takut', 'kali', 'labrak', 'mm', 'artis', 'kampungan', 'sih', 'ya', 'wajar', 'ya'], ['username', 'main', 'main', 'jawa', 'timur', 'biar', 'ga', 'begok'], ['username', 'nya', 'ngatain', 'org', 'nyindir', 'netijen', 'goblog', 'banyakan', 'masyako'], ['username', 'udah', 'nunjukin', 'karyanya', 'situ', 'pny', 'karya', 'karya', 'nyinyir', 'hidupnya', 'via', 'tolol'], ['username', 'bilang', 'gw', 'fansnya', 'via', 'duh', 'nantangin', 'gw', 'nih', 'org', 'anak', 'tolol', 'ank', 'alay', 'jablay'], ['username', 'yutub', 'ya', 'mba', 'aplikasi', 'ya', 'sy', 'taunya', 'youtube', 'mba', 'gak', 'tau', 'ya', 'seseorg', 'bs', 'dpt', 'penghasilan', 'salah', 'satunya', 'dr', 'youtube', 'loh', 'mreka', 'jg', 'bayar', 'klo', 'bnyk', 'yg', 'ntn', 'video', 'mreka', 'sekolah', 'yg', 'bener', 'deh', 'mba', 'biar', 'pinter', 'generasi', 'muda'], ['gue', 'suka', 'gangerti', 'deh', 'yaa', 'kalo', 'via', 'vallen', 'bikin', 'status', 'apalah', 'disangkut', 'pautin', 'ama', 'att', 'mulu', 'att', 'nya', 'aja', 'aja', 'fansnya', 'sih', 'yg', 'bikin', 'jelek', 'orang', 'kalo', 'sangkut', 'pautin', 'mulu', 'jg', 'gerah', 'kali'], ['jujur', 'aja', 'ya', 'ni', 'org', 'bagusan', 'kaga', 'oplasada', 'tu', 'foto', 'sblm', 'dn', 'oplasdioplas', 'mukanya', 'anehkyknya', 'gagal', 'oplasnya'], ['noraaak', 'abiiis', 'kebeli', 'emas', 'az', 'pamer', 'aplg', 'mainan', 'berlian', 'ciiinnnnn'], ['before', 'and', 'after', 'pasca', 'oplas', 'ga', 'ngefek', 'ya', 'tetep', 'jelek', 'n', 'serem', 'mukanyaahahahhaha'], ['salfok', 'mukanya', 'sumpah', 'jelek', 'oplas', 'model', 'failed'], ['norak', 'bener', 'kegaet', 'penjahat'], ['najisapalagi', 'd', 'philipine', 'bgt', 'kalid', 'aj', 'banggajd', 'perusak', 'moral', 'ko', 'bangganajis', 'banget', 'liatnyackp', 'd', 'aj', 'komen', 'nydia', 'pngn', 'ngetop', 'lwt', 'nitezerrrewkwkwkngarep', 'laku'], ['gua', 'bingung', 'jujur', 'media', 'rebutan', 'ngeliput', 'orang', 'kayaknya', 'cuman', 'net', 'doang', 'media', 'informasi', 'waras'], ['jedun', 'yg', 'ga', 'becus', 'perempuan', 'terhormat', 'ga', 'becus', 'perempuan', 'cerdas', 'ga', 'becus', 'perempuan', 'yg', 'mencari', 'suami', 'sah', 'suami', 'orang', 'ga', 'becus', 'perempuan', 'yg', 'menghindari', 'narkoba', 'ga', 'becus', 'perempuan', 'yg', 'menjaga', 'nama', 'keluarga', 'semoga', 'ada', 'perempuan', 'yg', 'kayak', 'dunia', 'ya', 'jedun'], ['cewe', 'yg', 'bgni', 'yg', 'hrsnya', 'gosong', 'jd', 'abu', 'aja', 'kebakaran', 'pabrik', 'yg', 'lg', 'viral', 'kmrn', 'tu', 'bnr', 'slain', 'ga', 'brguna', 'gda', 'otak', 'cm', 'modal', 'ngangkang', 'trs', 'gebet', 'laki', 'org', 'trs', 'bangga', 'btw', 'klo', 'emg', 'instastory', 'nya', 'nyindir', 'sesebini', 'tua', 'mah', 'ehhh', 'at', 'least', 'biar', 'ga', 'becus', 'jd', 'prewi', 'tp', 'becus', 'cuii', 'jd', 'emak', 'buktinya', 'anak', 'nya', 'bejibun', 'trs', 'smua', 'pro', 'emaknya', 'drpd', 'bapaknya'], ['hahahakasian', 'yagak', 'becus', 'peremharus', 'ngerebut', 'laki', 'orang', 'biar', 'dikata', 'perempuan', 'dasar', 'perempuan', 'sadar', 'ente', 'cuy'], ['dasar', 'artis', 'abal', 'abal', 'enggk', 'laku', 'layar', 'kacaudh', 'enggk', 'ada', 'duit', 'kere', 'miskinjadi', 'maen', 'k', 'dukun', 'elmu', 'pelet', 'perebut', 'suami', 'org', 'yg', 'kaya'], ['ih', 'becus', 'makrum', 'becus', 'ngrebut', 'suami', 'orang', 'he'], ['ee', 'si', 'pelacur', 'situ', 'becus', 'jd', 'brempuan', 'emang', 'becus', 'sampah', 'sih', 'iya', 'edeuuuuuh', 'lonte', 'lonte'], ['biarinpuas', 'puasin', 'mumpung', 'deseu', 'brasa', 'muda', 'ntar', 'klo', 'dah', 'tua', 'nyaho', 'karma', 'ada'], ['anak', 'perempuan', 'lho', 'contohin', 'jelek', 'anaknya', 'becus', 'perempuan', 'amit', 'amit'], ['kaya', 'becus', 'aja', 'jd', 'permpuan', 'yng', 'g', 'becus', 'jd', 'perempuan', 'ko', 'sukanya', 'sm', 'laki', 'orng', 'heheh'], ['yg', 'gk', 'becus', 'tuh', 'loh', 'jedunhidup', 'nya', 'bisanya', 'ngerusak', 'kbhgiaan', 'org', 'hidup', 'serba', 'mewah', 'tp', 'g', 'krja', 'mlh', 'morotin', 'laki', 'orgkarma', 'psti', 'akn', 'mnghampirimu'], ['gue', 'gak', 'suka', 'sm', 'ni', 'orang', 'idupnya', 'kebanyakan', 'ribut'], ['dasar', 'artis', 'abal', 'abal', 'enggk', 'laku', 'layar', 'kacaudh', 'enggk', 'ada', 'duit', 'kere', 'miskinjadi', 'maen', 'k', 'dukun', 'elmu', 'pelet', 'perebut', 'suami', 'org', 'yg', 'kaya'], ['yg', 'nama', 'ny', 'plagiat', 'ya', 'plagiat', 'laku', 'tp', 'tetep', 'ajah', 'ciptaan', 'dri', 'hasil', 'plagiatwkwkwkwk', 'gua', 'mah', 'ogah', 'dwngerin', 'ajah', 'udh', 'pngen', 'muntah'], ['dasar', 'plagiat', 'ga', 'kreatipmemalukab', 'bgt'], ['begonya', 'bilang', 'apanya', 'yaaa', 'liriknya', 'aja', 'percintaan', 'gitu', 'lagu', 'bener', 'tolol', 'si', 'ayu', 'gapunya', 'kuping', 'y', 'orang', 'yg', 'dipermasalahin', 'nadanya'], ['pacarnya', 'anggel', 'pietrs', 'kali', 'cowok', 'bocah', 'username', 'yaelah', 'jes', 'terxta', 'kelakuan', 'mu', 'aja', 'sprti', 'ayuting', 'hidupmu', 'penuh', 'drama', 'murahan'], ['japok', 'gateeel', 'emanguda', 'ada', 'main', 'si', 'mamadsampe', 'si', 'jessica', 'dimusuhindeddy', 'corbuzier', 'aja', 'jijik', 'si', 'japok', 'semenjak', 'nagita', 'diundang', 'hitam', 'putih', 'nagita', 'cerita', 'panggungitu', 'aja', 'sih', 'gue'], ['username', 'memalukan', 'buk', 'ngomong', 'pelakor', 'emang', 'ibuk', 'udah', 'pelakor', 'ya', 'tau', 'ayu', 'pelakor', 'wkwkwkwkwk', 'awas', 'rumah', 'tangga', 'yg', 'dimasukin', 'pelakor', 'anaknya', 'pelakor'], ['kerdus', 'mulutnya', 'busukjangan', 'sampah', 'makanannya'], ['username', 'tai', 'loe', 'gedein', 'bagus', 'pupuk', 'jngan', 'bacot', 'loe', 'goblok', 'nih', 'cewek', 'knpa', 'bawa', 'suku'], ['elo', 'artis', 'papan', 'blenyek', 'aja', 'belagu', 'artis', 'kga', 'populer', 'sekalu', 'hahaha'], ['anang', 'muka', 'nya', 'kaya', 'babiii', 'gitu', 'aja', 'demenin', 'jijikk'], ['ga', 'suka', 'ayu', 'ting', 'ting', 'ga', 'separah', 'ngejudge', 'nya', 'hati', 'otak', 'manusia', 'kekurangan', 'kelebihan', 'perasaan', 'seenak', 'nya', 'menjudge', 'orang', 'kaya', 'udah', 'sempurna', 'aja', 'lo', 'username'], ['ga', 'pantes', 'dipanggil', 'ustadorg', 'munafik', 'ceramah', 'org', 'kelakuan', 'sndr', 'aja', 'menzolimi', 'istri', 'sah', 'nya', 'dgn', 'poligami', 'diamkacian', 'istri', 'pertamanyaga', 'tw', 'malu', 'istri', 'hadeh', 'klo', 'ada', 'yg', 'msh', 'manggil', 'bwt', 'ceramah', 'namanya', 'bodo'], ['biadab', 'klo', 'anak', 'lo', 'bully', 'gue', 'mampusin', 'ya'], ['dasar', 'anjing', 'tuh', 'cowok', 'org', 'berani', 'cowok', 'one', 'by', 'one', 'yg', 'lemah', 'dasar', 'yah', 'cowok', 'jaman', 'skrg', 'casing', 'doank', 'cowok', 'nyali', 'nya', 'banci'], ['username', 'iya', 'kasian', 'si', 'micin', 'perusahan', 'produk', 'micin', 'mengiklan', 'kalo', 'masak', 'tambahkan', 'micin', 'biar', 'sedap', 'netizen', 'menyudutkan', 'mecin', 'kebodohan', 'orang', 'yg', 'gangguan', 'jiwa', 'ngemil', 'micinjusticeformicin'], ['wahh', 'jngn', 'vidio', 'lamakok', 'bajunya', 'norak', 'bngtt', 'ayuuterlihat', 'murahaan'], ['username', 'bego', 'lo', 'ya'], ['editan', 'banget', 'ya', 'ampun', 'si', 'mommy', 'lambe', 'kehabisan', 'gosib', 'ya', 'si', 'pelakor'], ['yah', 'admin', 'nya', 'golongan', 'pengonsumsi', 'mecin', 'pil', 'pcc', 'otak', 'lu', 'rusak', 'min'], ['org', 'govlok', 'yg', 'prcya', 'ayu', 'slgkuh', 'sma', 'rafibuktinya', 'rafi', 'sma', 'gi', 'skrg', 'baek', 'ajadan', 'ktamu', 'ayu', 'pela

In [28]:
word_counts = Counter(list_of_token)

for word, count in word_counts.most_common(100):
  print(f"{word}: {count}")

yg: 211
username: 86
nya: 85
ya: 85
ga: 77
aja: 67
gak: 63
ada: 55
anak: 54
orang: 53
banget: 47
si: 44
artis: 42
org: 41
semoga: 40
cantik: 39
bgt: 34
jd: 34
kaya: 33
udah: 31
kalo: 29
suka: 29
mba: 29
klo: 28
sm: 27
suami: 26
lo: 25
sih: 24
laki: 24
lu: 24
allah: 24
mbak: 23
tau: 23
jg: 23
biar: 22
udh: 22
pelakor: 22
istri: 22
keluarga: 22
n: 22
pake: 21
deh: 21
bagus: 21
tp: 21
nikah: 20
sok: 20
ama: 20
manusia: 19
gue: 19
ganteng: 19
bilang: 18
sehat: 18
skrg: 17
becus: 17
ayu: 17
perempuan: 17
lg: 16
anaknya: 16
suaranya: 16
dunia: 16
tuh: 15
kali: 15
dr: 15
gitu: 15
dasar: 15
mah: 15
keren: 15
otak: 14
bener: 14
d: 14
bikin: 14
emang: 14
bego: 13
ni: 13
bahagia: 13
aurel: 13
att: 12
jijik: 12
mukanya: 12
liat: 12
kampungan: 12
gw: 12
jevin: 12
kek: 11
jaman: 11
malu: 11
ma: 11
yaa: 11
ny: 11
muda: 11
kayak: 11
jgn: 11
y: 11
tu: 11
gk: 10
krn: 10
nih: 10
gua: 10
aj: 10
g: 10

In [29]:
from nltk.util import ngrams

bigram = ngrams(list_of_token,2)
bigram_count = Counter(bigram)

for bigram, count in bigram_count.most_common(20):
  print(f"{bigram[0]} {bigram[1]} = {count}")

gak ada = 8
ada yg = 8
jaman now = 6
biar ga = 6
ga becus = 6
becus perempuan = 6
anak nya = 6
org yg = 6
allah swt = 6
dunia akhirat = 5
bgt sm = 5
perempuan yg = 5
laki orang = 5
yg suka = 5
ga ada = 5
artis yg = 5
yg yg = 4
kids jaman = 4
nya yg = 4
sok suci = 4

Dari cek kata yang sering keluar dan pasangan kata yang sering keluar, kita bisa rapihkan kata" yang merupakan slang atau singkatan dari bahasa Indonesia. da dibawah ini ada banyak kata yang kita rapihkan.

In [38]:
word_dict = {
    "ga":"tidak",
    "gak":"tidak",
    "kalo":"jika",
    "pelakor": "perebut laki orang",
    "bgt" : "sangat",
    "dgn": "dengan",
    "tp":"tapi",
    "sok":"sombong",
    "dr":"dari",
    "gw":"saya",
    'gua':'saya',
    'gue':'saya',
    "bener":"benar",
    "sy":"saya",
    'lo':'kamu',
    'lu':'kamu',
    'org':'orang',
    'n':'dan',
    'pake':'pakai',
    'jd':'jadi',
    'laki':'pria',
    'sm':'sama',
    'yg':'yang',
    'tau':'tahu',
    'd':'di',
    'tolol':'bodoh',
    'bego':'bodoh',
    'att':'atitut',
    'jgn':'jangan',
    'y':'ya',
    'tu':'tuh',
    'krn':'karena',
    'jaman':'zaman',
    'aj':'saja',
    'g':'tidak',
    'now':'sekarang',
    'biar':'agar',
    'geblek':'bodoh',
    'kmrn':'kemarin',
    'skrg':'sekarang',
    'apaoun':'apapun',
    'trus':'lalu'
}

def fix_slang(sentence, word_dict):
  tokens = word_tokenize(sentence)
  fix_slangs = [word_dict.get(word, word) for word in tokens]
  return ' '.join(fix_slangs)

In [109]:
data['text_non_slang']  = data['text_non_stopword'] .apply(lambda x: fix_slang(x, word_dict))
data

,Id,Sentiment,Instagram Comment Text,text_cleaned,text_non_stopword,text_non_slang
0,1,negative,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,username tolol gak ada hubungan nya keguguran ...,username bodoh tidak ada hubungan nya kegugura...
1,2,negative,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tatacowo bgt dibelain balikanhadewwn...,geblek lo tatacowo bgt dibelain balikanhadewwn...,bodoh kamu tatacowo sangat dibelain balikanhad...
2,3,negative,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,kmrn termewek skr lengket lg duhhh labil bgt s...,kemarin termewek skr lengket lg duhhh labil sa...
3,4,negative,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,intinya kesel att nya gausah anaknya kasian pe...,intinya kesel atitut nya gausah anaknya kasian...
4,5,negative,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lgsakit jiwaknp harus d...,hadewwwww permpuan lgsakit jiwaknp yg jd peran...,hadewwwww permpuan lgsakit jiwaknp yang jadi p...
...,...,...,...,...,...,...
395,396,positive,Bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...,bangga suami yg istri disela apapun profesimu ...,bangga suami yang istri disela apapun profesim...
396,397,positive,Apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg halal u tuk menafkahi k...,apapun pekerjaannya yang halal u tuk menafkahi...
397,398,positive,Gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...,gojek mayoritas pegangguran gak kerja trus put...,gojek mayoritas pegangguran tidak kerja lalu p...
398,399,positive,<USERNAME> aslinya cantik dan ayu loh mbak kr...,username aslinya cantik dan ayu loh mbak krn a...,username aslinya cantik ayu loh mbak krn berte...,username aslinya cantik ayu loh mbak karena be...
399,400,positive,"<USERNAME> suami saya seumuran sama saya mba,...",username suami saya seumuran sama saya mba mal...,username suami seumuran mba tuaan alhamdulilla...,username suami seumuran mba tuaan alhamdulilla...

Setelah dapat hasil bersihnya bari bisa kita lanjutkan ke 2 Metode yang akan kita bandingkan

## METODE NAIVE BAYES

[Kata Positif](https://drive.google.com/file/d/1YW3fqnBDeBa6-UF5HjZWCjqbENOwdSqp/view?usp=drive_link)
[Kata Negatif](https://drive.google.com/file/d/1mJkAtp0rWRSZnpvH0JwC27fZCKvF_UXP/view?usp=drive_link)

In [40]:
with open("./kata positif.txt","r") as positif_file :
  positive_words = list(set(positif_file.readlines()))

with open("./kata negatif.txt","r") as negative_file :
  negative_words = list(set(negative_file.readlines()))

In [41]:
positive_words = [word.rstrip() for word in positive_words]
negative_words = [word.rstrip() for word in negative_words]

print(positive_words[:10])
print(negative_words[:10])

['dipathui', 'sportivitas', 'pencarian', 'dikokohkan', 'dibekali', 'hormat', 'tersukses', 'loyal', 'tuntas', 'mempersukses']
['tsunami', 'ugal-ugalan', 'traumatis', 'cidera', 'goyah', 'menangisi', 'kecelakaan', 'dimandulkan', 'mengorbankan', 'asal bunyi']

In [48]:
def sentiment_counts(text, positive_words, negative_words):
  good_count = 0
  bad_count = 0

  tokens = word_tokenize(text)

  for token in tokens:
        if token in positive_words:
            good_count += 1
        if token in negative_words:
            bad_count += 1

  return good_count - bad_count

In [49]:
data['count'] = data['text_non_slang'].apply(lambda x: sentiment_counts(x, positive_words, negative_words))

In [50]:
data

,Id,Sentiment,Instagram Comment Text,text_cleaned,text_non_stopword,text_non_slang,count
0,1,negative,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,username tolol gak ada hubungan nya keguguran ...,username bodoh tidak ada hubungan nya kegugura...,-3
1,2,negative,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tatacowo bgt dibelain balikanhadewwn...,geblek lo tatacowo bgt dibelain balikanhadewwn...,bodoh kamu tatacowo sangat dibelain balikanhad...,-1
2,3,negative,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,kmrn termewek skr lengket lg duhhh labil bgt s...,kemarin termewek skr lengket lg duhhh labil sa...,0
3,4,negative,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,intinya kesel att nya gausah anaknya kasian pe...,intinya kesel atitut nya gausah anaknya kasian...,1
4,5,negative,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lgsakit jiwaknp harus d...,hadewwwww permpuan lgsakit jiwaknp yg jd peran...,hadewwwww permpuan lgsakit jiwaknp yang jadi p...,-1
...,...,...,...,...,...,...,...
395,396,positive,Bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...,bangga suami yg istri disela apapun profesimu ...,bangga suami yang istri disela apapun profesim...,3
396,397,positive,Apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg halal u tuk menafkahi k...,apapun pekerjaannya yang halal u tuk menafkahi...,2
397,398,positive,Gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...,gojek mayoritas pegangguran gak kerja trus put...,gojek mayoritas pegangguran tidak kerja lalu p...,3
398,399,positive,<USERNAME> aslinya cantik dan ayu loh mbak kr...,username aslinya cantik dan ayu loh mbak krn a...,username aslinya cantik ayu loh mbak krn berte...,username aslinya cantik ayu loh mbak karena be...,1
399,400,positive,"<USERNAME> suami saya seumuran sama saya mba,...",username suami saya seumuran sama saya mba mal...,username suami seumuran mba tuaan alhamdulilla...,username suami seumuran mba tuaan alhamdulilla...,1

pada kolom count, bisa kita lihat banyak angka yang menunjukkan kearah mana kalimat di depannya positif atau negatif. jadi kita buat kolom sendiri yang dapat memberikan hasil sentimennya.

In [51]:
def sentimen(score):
  if score > 0:
    return "positif"
  elif score == 0:
    return "netral"
  else:
    return "negatif"

In [52]:
data['hasil sentimen'] = data['count'].apply(sentimen)
data

,Id,Sentiment,Instagram Comment Text,text_cleaned,text_non_stopword,text_non_slang,count,hasil sentimen
0,1,negative,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,username tolol gak ada hubungan nya keguguran ...,username bodoh tidak ada hubungan nya kegugura...,-3,negatif
1,2,negative,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tatacowo bgt dibelain balikanhadewwn...,geblek lo tatacowo bgt dibelain balikanhadewwn...,bodoh kamu tatacowo sangat dibelain balikanhad...,-1,negatif
2,3,negative,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,kmrn termewek skr lengket lg duhhh labil bgt s...,kemarin termewek skr lengket lg duhhh labil sa...,0,netral
3,4,negative,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,intinya kesel att nya gausah anaknya kasian pe...,intinya kesel atitut nya gausah anaknya kasian...,1,positif
4,5,negative,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lgsakit jiwaknp harus d...,hadewwwww permpuan lgsakit jiwaknp yg jd peran...,hadewwwww permpuan lgsakit jiwaknp yang jadi p...,-1,negatif
...,...,...,...,...,...,...,...,...
395,396,positive,Bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...,bangga suami yg istri disela apapun profesimu ...,bangga suami yang istri disela apapun profesim...,3,positif
396,397,positive,Apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg halal u tuk menafkahi k...,apapun pekerjaannya yang halal u tuk menafkahi...,2,positif
397,398,positive,Gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...,gojek mayoritas pegangguran gak kerja trus put...,gojek mayoritas pegangguran tidak kerja lalu p...,3,positif
398,399,positive,<USERNAME> aslinya cantik dan ayu loh mbak kr...,username aslinya cantik dan ayu loh mbak krn a...,username aslinya cantik ayu loh mbak krn berte...,username aslinya cantik ayu loh mbak karena be...,1,positif
399,400,positive,"<USERNAME> suami saya seumuran sama saya mba,...",username suami saya seumuran sama saya mba mal...,username suami seumuran mba tuaan alhamdulilla...,username suami seumuran mba tuaan alhamdulilla...,1,positif

In [53]:
data['hasil sentimen'].value_counts()

hasil sentimen
positif    172
negatif    123
netral     105
Name: count, dtype: int64

Melalui Metode Naive Bayes, Hasil Positif dari dataset Training yang saya gunakan ada 172. Negatif di 123 dan Netral di 105.

##METODE LEXICON

Kita coba data yang sama tapi dengam metode yang berbeda
[Positif Lexicon](https://drive.google.com/file/d/1JnwJW4aQCJTZ5N2gtSOb-Dmcu1Pnamt8/view?usp=drive_link)
[Negatif Lexicon](https://drive.google.com/file/d/1gQRv8cFpBDNSPy5MYUzo3d-Z4Aaswl_M/view?usp=drive_link)

In [57]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

with open("./lex positif.txt","r") as positif_file :
  positive_words_lex = list(set(positif_file.readlines()))

with open("./lex negatif.txt","r") as negative_file :
  negative_words_lex = list(set(negative_file.readlines()))

positive_lex = [word.rstrip() for word in positive_words_lex]
negative_lex = [word.rstrip() for word in negative_words_lex]

In [58]:
def sentiment_counts_lex(text, positive_lex, negative_lex, stemmer):

  tokens = word_tokenize(text)
  stemmed_tokens = [stemmer.stem(token) for token in tokens]

  positive_count = 0
  negative_count = 0

  for token in stemmed_tokens:
        if token in positive_lex:
            positive_count += 1
        if token in negative_lex:
            negative_count += 1

  sentiment_score = positive_count - negative_count

  if sentiment_score > 0:
        return "positive"
  elif sentiment_score == 0:
        return "neutral"
  else:
        return "negative"

In [61]:
data['lexicon_sentiment'] = data['text_non_slang'].apply(lambda x: sentiment_counts_lex(x, positive_lex, negative_lex, stemmer))
data

,Id,Sentiment,Instagram Comment Text,text_cleaned,text_non_stopword,text_non_slang,count,hasil sentimen,lexicon_sentiment
0,1,negative,<USERNAME> TOLOL!! Gak ada hubungan nya kegug...,username tolol gak ada hubungan nya keguguran ...,username tolol gak ada hubungan nya keguguran ...,username bodoh tidak ada hubungan nya kegugura...,-3,negatif,negative
1,2,negative,Geblek lo tata...cowo bgt dibela2in balikan......,geblek lo tatacowo bgt dibelain balikanhadewwn...,geblek lo tatacowo bgt dibelain balikanhadewwn...,bodoh kamu tatacowo sangat dibelain balikanhad...,-1,negatif,negative
2,3,negative,Kmrn termewek2 skr lengket lg duhhh kok labil ...,kmrn termewek skr lengket lg duhhh kok labil b...,kmrn termewek skr lengket lg duhhh labil bgt s...,kemarin termewek skr lengket lg duhhh labil sa...,0,netral,negative
3,4,negative,"Intinya kalau kesel dengan ATT nya, gausah ke ...",intinya kalau kesel dengan att nya gausah ke a...,intinya kesel att nya gausah anaknya kasian pe...,intinya kesel atitut nya gausah anaknya kasian...,1,positif,negative
4,5,negative,"hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...",hadewwwww permpuan itu lgsakit jiwaknp harus d...,hadewwwww permpuan lgsakit jiwaknp yg jd peran...,hadewwwww permpuan lgsakit jiwaknp yang jadi p...,-1,negatif,neutral
...,...,...,...,...,...,...,...,...,...
395,396,positive,Bangga sama suami yg selalu ingat istri disela...,bangga sama suami yg selalu ingat istri disela...,bangga suami yg istri disela apapun profesimu ...,bangga suami yang istri disela apapun profesim...,3,positif,positive
396,397,positive,Apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg penting halal u tuk men...,apaoun pekerjaannya yg halal u tuk menafkahi k...,apapun pekerjaannya yang halal u tuk menafkahi...,2,positif,positive
397,398,positive,Gojek itu mayoritas pegangguran yang lama gak ...,gojek itu mayoritas pegangguran yang lama gak ...,gojek mayoritas pegangguran gak kerja trus put...,gojek mayoritas pegangguran tidak kerja lalu p...,3,positif,neutral
398,399,positive,<USERNAME> aslinya cantik dan ayu loh mbak kr...,username aslinya cantik dan ayu loh mbak krn a...,username aslinya cantik ayu loh mbak krn berte...,username aslinya cantik ayu loh mbak karena be...,1,positif,positive
399,400,positive,"<USERNAME> suami saya seumuran sama saya mba,...",username suami saya seumuran sama saya mba mal...,username suami seumuran mba tuaan alhamdulilla...,username suami seumuran mba tuaan alhamdulilla...,1,positif,neutral

In [62]:
data['lexicon_sentiment'].value_counts()

lexicon_sentiment
positive    154
negative    151
neutral      95
Name: count, dtype: int64

Proses yang sama tapi hasil yang berbeda walaupun tetap komentar sentimen positif ada di nomor 1, diikuti oleh negatif dan netral. Hasil disini jauh lebih kompetitif

## Sentiment Analysis pada komentar di postingan IG [Indozone ID](https://www.instagram.com/p/DEmxFKTzfqm/)

Ayo kita coba dengan 50 komentar acak dari postingan di IG Indozone diatas [Komentar Indozone](https://drive.google.com/file/d/1hTv6Ts6gVEsJwRUn3jVFh4jpNlDgRwmv/view?usp=drive_link)

In [82]:
with open('Komentar Indozone txt.txt', 'r') as file:
    komentar_indozone = file.readlines()

df = pd.DataFrame(komentar_indozone, columns=['Instagram Comment Text'])
print(df)

                               Instagram Comment Text
0                           ﻿Instagram Comment Text\n
1   Setiap mau Ramadhan sama IdulFitri ada aja pro...
2               Penyakit mematikan itu adalah Media\n
3                         Hahahah berita jancok ini\n
4   Apaan si media bikin ribet bae di cina biasa2 ...
5   Kata teman gua yg tinggal dichina dsna B aja c...
6   Heran aku heran tadi pas natal dan tahun baru ...
7   Media2 memperkeruh kalo emg di anggap biasa aj...
8                    Media emang suka nakut-nakutin\n
9   Yg nama a perubahan cuaca uda pasti sakit apa ...
10               di indo langsung jadi lahan bisnis\n
11  Kami di malaysia ga ada apa2 ga ada dngr kata2...
12  BODO AMAT !!! Setiap mau puasa setiap mau leba...
13  Beritanya jangan yang bikin takut saya lagi ca...
14  Byk di yutube org org indo yg di cina bilang g...
15  Apaan banyak video orang indo di China pada bi...
16  ya elaah, yakali gue sakit tenggorokan gara2 b...
17  Bisnis yang menguntungkan adalah Bisnis yang m...
18  Cina lagi cina lagi GK bosen apa cina ngekspor...
19  Bodo amat yang penting saya tetap mudik lebara...
20  GW BODO AMAT MIN.. GW LEBIH PERCAYA MATI KAREN...
21  Ga use digoreng2 dah, statement nya aja sama k...
22           Virus sekarang nyebarnya melalui media\n
23                         Apalagi ini... Heduftttt\n
24                         Hah ada trend virus lagi\n
25                                   lumayan proyek\n
26                            Hati hati warga depok\n
27              Nyari balik modal kemaren nyoblos..\n
28  Maaf ikut nanya, gmn ya cara ngempesin perut b...
29        SAATNYA DOKTER KEMBALI MERAUP PUNDI PUNDI\n
30                                            Bacot\n
31  Yuhhuuu menyala Abang ku sekolah libur lagi 3t...
32  Ada vloger yg udh pergi ke china dan dia memba...
33  Udah ketebak kan arahnya kemana template bgt, ...
34  "Wkwk sodara gue yg jadi TKW sana bilang ga ad...
35  Di china bawa virus mulu heran, bawa virus kek...
36  Virus Bisnis yg terstruktur. Abaikan Dan gak u...
37  Percaya? Mendingan gw ajak debat by data aj sa...
38  Maaf min lg bnyak urussn,gua dulu dah vaksin j...
39  Tiap mau puasa kok virus baru, mau larang oran...
40  Timbang batuk pilek di bilang wabah.. KORUPSI ...
41  Event apa lagi ini mau dekat ramadhan dan leba...
42  Bentar LG lebaran ya,jgn dikasih panggung brit...
43     banyak fomo nih, jadi rame kan penyakit nya.\n
44          Yg lagi travelling tiati pulang ke Indo\n
45  Ini yang bener yang mana beritanya??? Kemenkes...
46  Mana ada di China baik baik aja bos. Gak usah ...
47                  Virus Garuda enak pake ketoprak\n
48                         Yailah bilang aja radang\n
49   kalo disini namanya meriang, dah ada dari dulu\n
50  Rakyat indo harus kompak,kita tidak muw di bod...

Ternyata Kolom Pertamanya masih ikut dan mari kita drop

In [83]:
df= df.drop(index=0)
df

                               Instagram Comment Text
1   Setiap mau Ramadhan sama IdulFitri ada aja pro...
2               Penyakit mematikan itu adalah Media\n
3                         Hahahah berita jancok ini\n
4   Apaan si media bikin ribet bae di cina biasa2 ...
5   Kata teman gua yg tinggal dichina dsna B aja c...
6   Heran aku heran tadi pas natal dan tahun baru ...
7   Media2 memperkeruh kalo emg di anggap biasa aj...
8                    Media emang suka nakut-nakutin\n
9   Yg nama a perubahan cuaca uda pasti sakit apa ...
10               di indo langsung jadi lahan bisnis\n
11  Kami di malaysia ga ada apa2 ga ada dngr kata2...
12  BODO AMAT !!! Setiap mau puasa setiap mau leba...
13  Beritanya jangan yang bikin takut saya lagi ca...
14  Byk di yutube org org indo yg di cina bilang g...
15  Apaan banyak video orang indo di China pada bi...
16  ya elaah, yakali gue sakit tenggorokan gara2 b...
17  Bisnis yang menguntungkan adalah Bisnis yang m...
18  Cina lagi cina lagi GK bosen apa cina ngekspor...
19  Bodo amat yang penting saya tetap mudik lebara...
20  GW BODO AMAT MIN.. GW LEBIH PERCAYA MATI KAREN...
21  Ga use digoreng2 dah, statement nya aja sama k...
22           Virus sekarang nyebarnya melalui media\n
23                         Apalagi ini... Heduftttt\n
24                         Hah ada trend virus lagi\n
25                                   lumayan proyek\n
26                            Hati hati warga depok\n
27              Nyari balik modal kemaren nyoblos..\n
28  Maaf ikut nanya, gmn ya cara ngempesin perut b...
29        SAATNYA DOKTER KEMBALI MERAUP PUNDI PUNDI\n
30                                            Bacot\n
31  Yuhhuuu menyala Abang ku sekolah libur lagi 3t...
32  Ada vloger yg udh pergi ke china dan dia memba...
33  Udah ketebak kan arahnya kemana template bgt, ...
34  "Wkwk sodara gue yg jadi TKW sana bilang ga ad...
35  Di china bawa virus mulu heran, bawa virus kek...
36  Virus Bisnis yg terstruktur. Abaikan Dan gak u...
37  Percaya? Mendingan gw ajak debat by data aj sa...
38  Maaf min lg bnyak urussn,gua dulu dah vaksin j...
39  Tiap mau puasa kok virus baru, mau larang oran...
40  Timbang batuk pilek di bilang wabah.. KORUPSI ...
41  Event apa lagi ini mau dekat ramadhan dan leba...
42  Bentar LG lebaran ya,jgn dikasih panggung brit...
43     banyak fomo nih, jadi rame kan penyakit nya.\n
44          Yg lagi travelling tiati pulang ke Indo\n
45  Ini yang bener yang mana beritanya??? Kemenkes...
46  Mana ada di China baik baik aja bos. Gak usah ...
47                  Virus Garuda enak pake ketoprak\n
48                         Yailah bilang aja radang\n
49   kalo disini namanya meriang, dah ada dari dulu\n
50  Rakyat indo harus kompak,kita tidak muw di bod...

## Pembersihan Data Komentar

dengan metode yang sama seperti data training kita jalankan pembersihannya

In [84]:
df['text_cleaned'] = df['Instagram Comment Text'].apply(text_cleaning)
df

,Instagram Comment Text,text_cleaned
1,Setiap mau Ramadhan sama IdulFitri ada aja pro...,setiap mau ramadhan sama idulfitri ada aja pro...
2,Penyakit mematikan itu adalah Media\n,penyakit mematikan itu adalah media
3,Hahahah berita jancok ini\n,hahahah berita jancok ini
4,Apaan si media bikin ribet bae di cina biasa2 ...,apaan si media bikin ribet bae di cina biasa a...
5,Kata teman gua yg tinggal dichina dsna B aja c...,kata teman gua yg tinggal dichina dsna b aja c...
6,Heran aku heran tadi pas natal dan tahun baru ...,heran aku heran tadi pas natal dan tahun baru ...
7,Media2 memperkeruh kalo emg di anggap biasa aj...,media memperkeruh kalo emg di anggap biasa aja...
8,Media emang suka nakut-nakutin\n,media emang suka nakutnakutin
9,Yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda pasti sakit apa ...
10,di indo langsung jadi lahan bisnis\n,di indo langsung jadi lahan bisnis
11,Kami di malaysia ga ada apa2 ga ada dngr kata2...,kami di malaysia ga ada apa ga ada dngr kata v...
12,BODO AMAT !!! Setiap mau puasa setiap mau leba...,bodo amat setiap mau puasa setiap mau lebaran ...
13,Beritanya jangan yang bikin takut saya lagi ca...,beritanya jangan yang bikin takut saya lagi ca...
14,Byk di yutube org org indo yg di cina bilang g...,byk di yutube org org indo yg di cina bilang g...
15,Apaan banyak video orang indo di China pada bi...,apaan banyak video orang indo di china pada bi...
16,"ya elaah, yakali gue sakit tenggorokan gara2 b...",ya elaah yakali gue sakit tenggorokan gara ban...
17,Bisnis yang menguntungkan adalah Bisnis yang m...,bisnis yang menguntungkan adalah bisnis yang m...
18,Cina lagi cina lagi GK bosen apa cina ngekspor...,cina lagi cina lagi gk bosen apa cina ngekspor...
19,Bodo amat yang penting saya tetap mudik lebara...,bodo amat yang penting saya tetap mudik lebaran
20,GW BODO AMAT MIN.. GW LEBIH PERCAYA MATI KAREN...,gw bodo amat min gw lebih percaya mati karena ...
21,"Ga use digoreng2 dah, statement nya aja sama k...",ga use digoreng dah statement nya aja sama kay...
22,Virus sekarang nyebarnya melalui media\n,virus sekarang nyebarnya melalui media
23,Apalagi ini... Heduftttt\n,apalagi ini heduftttt
24,Hah ada trend virus lagi\n,hah ada trend virus lagi
25,lumayan proyek\n,lumayan proyek
26,Hati hati warga depok\n,hati hati warga depok
27,Nyari balik modal kemaren nyoblos..\n,nyari balik modal kemaren nyoblos
28,"Maaf ikut nanya, gmn ya cara ngempesin perut b...",maaf ikut nanya gmn ya cara ngempesin perut bu...
29,SAATNYA DOKTER KEMBALI MERAUP PUNDI PUNDI\n,saatnya dokter kembali meraup pundi pundi
30,Bacot\n,bacot
31,Yuhhuuu menyala Abang ku sekolah libur lagi 3t...,yuhhuuu menyala abang ku sekolah libur lagi tahun
32,Ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi ke china dan dia memba...
33,"Udah ketebak kan arahnya kemana template bgt, ...",udah ketebak kan arahnya kemana template bgt b...
34,"""Wkwk sodara gue yg jadi TKW sana bilang ga ad...",wk sodara gue yg jadi tkw sana bilang ga ada v...
35,"Di china bawa virus mulu heran, bawa virus kek...",di china bawa virus mulu heran bawa virus keka...
36,Virus Bisnis yg terstruktur. Abaikan Dan gak u...,virus bisnis yg terstruktur abaikan dan gak us...
37,Percaya? Mendingan gw ajak debat by data aj sa...,percaya mendingan gw ajak debat by data aj sam...
38,"Maaf min lg bnyak urussn,gua dulu dah vaksin j...",maaf min lg bnyak urussngua dulu dah vaksin ju...
39,"Tiap mau puasa kok virus baru, mau larang oran...",tiap mau puasa kok virus baru mau larang orang...
40,Timbang batuk pilek di bilang wabah.. KORUPSI ...,timbang batuk pilek di bilang wabah korupsi tu...
41,Event apa lagi ini mau dekat ramadhan dan leba...,event apa lagi ini mau dekat ramadhan dan lebaran
42,"Bentar LG lebaran ya,jgn dikasih panggung brit...",bentar lg lebaran yajgn dikasih panggung brita...
43,"banyak fomo nih, jadi rame kan penyakit nya.\n",banyak fomo nih jadi rame kan penyakit nya
44,Yg lagi travelling tiati pulang ke Indo\n,yg lagi travelling tiati pulang ke indo
45,Ini yang bener yang mana beritanya??? Kemenkes...,ini yang bener yang mana beritanya kemenkes bi...
46,Mana ada di China baik baik aja bos. Gak usah ...,mana ada di china baik baik aja bos gak usah d...
47,Virus Garuda enak pake ketoprak\n,virus garuda enak pake ketoprak
48,Yailah bilang aja radang\n,yailah bilang aja radang
49,"kalo disini namanya meriang, dah ada dari dulu\n",kalo disini namanya meriang dah ada dari dulu
50,"Rakyat indo harus kompak,kita tidak muw di bod...",rakyat indo harus kompakkita tidak muw di bodo...

In [85]:
df['text_non_stopword'] = df['text_cleaned'].apply(stopword_cleaning, stopword_set=stopword_sets)
df

,Instagram Comment Text,text_cleaned,text_non_stopword
1,Setiap mau Ramadhan sama IdulFitri ada aja pro...,setiap mau ramadhan sama idulfitri ada aja pro...,ramadhan idulfitri ada aja program virus ya
2,Penyakit mematikan itu adalah Media\n,penyakit mematikan itu adalah media,penyakit mematikan media
3,Hahahah berita jancok ini\n,hahahah berita jancok ini,hahahah berita jancok
4,Apaan si media bikin ribet bae di cina biasa2 ...,apaan si media bikin ribet bae di cina biasa a...,si media bikin ribet bae cina aja jg ga bikin ...
5,Kata teman gua yg tinggal dichina dsna B aja c...,kata teman gua yg tinggal dichina dsna b aja c...,teman gua yg tinggal dichina dsna b aja indo a...
6,Heran aku heran tadi pas natal dan tahun baru ...,heran aku heran tadi pas natal dan tahun baru ...,heran heran pas natal kemana aja giliran ramad...
7,Media2 memperkeruh kalo emg di anggap biasa aj...,media memperkeruh kalo emg di anggap biasa aja...,media memperkeruh kalo emg anggap aja udah sto...
8,Media emang suka nakut-nakutin\n,media emang suka nakutnakutin,media emang suka nakutnakutin
9,Yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda sakit imun lemah...
10,di indo langsung jadi lahan bisnis\n,di indo langsung jadi lahan bisnis,indo langsung lahan bisnis
11,Kami di malaysia ga ada apa2 ga ada dngr kata2...,kami di malaysia ga ada apa ga ada dngr kata v...,malaysia ga ada ga ada dngr virus temen yg chi...
12,BODO AMAT !!! Setiap mau puasa setiap mau leba...,bodo amat setiap mau puasa setiap mau lebaran ...,bodo puasa lebaran ada aja ora percaya
13,Beritanya jangan yang bikin takut saya lagi ca...,beritanya jangan yang bikin takut saya lagi ca...,beritanya bikin takut cari uang enak enak ya a...
14,Byk di yutube org org indo yg di cina bilang g...,byk di yutube org org indo yg di cina bilang g...,byk yutube org org indo yg cina bilang gak seg...
15,Apaan banyak video orang indo di China pada bi...,apaan banyak video orang indo di china pada bi...,video orang indo china aja menjalani kehidupan...
16,"ya elaah, yakali gue sakit tenggorokan gara2 b...",ya elaah yakali gue sakit tenggorokan gara ban...,ya elaah yakali gue sakit tenggorokan gara mak...
17,Bisnis yang menguntungkan adalah Bisnis yang m...,bisnis yang menguntungkan adalah bisnis yang m...,bisnis menguntungkan bisnis menjual ketakutan
18,Cina lagi cina lagi GK bosen apa cina ngekspor...,cina lagi cina lagi gk bosen apa cina ngekspor...,cina cina gk bosen cina ngekspor virus mulu
19,Bodo amat yang penting saya tetap mudik lebara...,bodo amat yang penting saya tetap mudik lebaran,bodo mudik lebaran
20,GW BODO AMAT MIN.. GW LEBIH PERCAYA MATI KAREN...,gw bodo amat min gw lebih percaya mati karena ...,gw bodo min gw percaya mati kelaparan virus
21,"Ga use digoreng2 dah, statement nya aja sama k...",ga use digoreng dah statement nya aja sama kay...,ga use digoreng dah statement nya aja kaya flu
22,Virus sekarang nyebarnya melalui media\n,virus sekarang nyebarnya melalui media,virus nyebarnya media
23,Apalagi ini... Heduftttt\n,apalagi ini heduftttt,heduftttt
24,Hah ada trend virus lagi\n,hah ada trend virus lagi,hah ada trend virus
25,lumayan proyek\n,lumayan proyek,lumayan proyek
26,Hati hati warga depok\n,hati hati warga depok,hati hati warga depok
27,Nyari balik modal kemaren nyoblos..\n,nyari balik modal kemaren nyoblos,nyari modal kemaren nyoblos
28,"Maaf ikut nanya, gmn ya cara ngempesin perut b...",maaf ikut nanya gmn ya cara ngempesin perut bu...,maaf nanya gmn ya ngempesin perut buncit yg ef...
29,SAATNYA DOKTER KEMBALI MERAUP PUNDI PUNDI\n,saatnya dokter kembali meraup pundi pundi,dokter meraup pundi pundi
30,Bacot\n,bacot,bacot
31,Yuhhuuu menyala Abang ku sekolah libur lagi 3t...,yuhhuuu menyala abang ku sekolah libur lagi tahun,yuhhuuu menyala abang ku sekolah libur
32,Ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi china membagikan video...
33,"Udah ketebak kan arahnya kemana template bgt, ...",udah ketebak kan arahnya kemana template bgt b...,udah ketebak arahnya kemana template bgt belaj...
34,"""Wkwk sodara gue yg jadi TKW sana bilang ga ad...",wk sodara gue yg jadi tkw sana bilang ga ada v...,wk sodara gue yg tkw bilang ga ada virus temen...
35,"Di china bawa virus mulu heran, bawa virus kek...",di china bawa virus mulu heran bawa virus keka...,china bawa virus mulu heran bawa virus kekayaa...
36,Virus Bisnis yg terstruktur. Abaikan Dan gak u...,virus bisnis yg terstruktur abaikan dan gak us...,virus bisnis yg terstruktur abaikan gak diberi...
37,Percaya? Mendingan gw ajak debat by data aj sa...,percaya mendingan gw ajak debat by data aj sam...,percaya mendingan gw ajak debat by data aj men...
38,"Maaf min lg bnyak urussn,gua dulu dah vaksin j...",maaf min lg bnyak urussngua dulu dah vaksin ju...,maaf min lg bnyak urussngua dah vaksin msa msi...
39,"Tiap mau puasa kok virus baru, mau larang oran...",tiap mau puasa kok virus baru mau larang orang...,puasa virus larang orang sholat berjamaah ya
40,Timbang batuk pilek di bilang wabah.. KORUPSI ...,timbang batuk pilek di bilang wabah korupsi tu...,timbang batuk pilek bilang wabah korupsi tuh w...
41,Event apa lagi ini mau dekat ramadhan dan leba...,event apa lagi ini mau dekat ramadhan dan lebaran,event ramadhan lebaran
42,"Bentar LG lebaran ya,jgn dikasih panggung brit...",bentar lg lebaran yajgn dikasih panggung brita...,bentar lg lebaran yajgn dikasih panggung brita...
43,"banyak fomo nih, jadi rame kan penyakit nya.\n",banyak fomo nih jadi rame kan penyakit nya,fomo nih rame penyakit nya
44,Yg lagi travelling tiati pulang ke Indo\n,yg lagi travelling tiati pulang ke indo,yg travelling tiati pulang indo
45,Ini yang bener yang mana beritanya??? Kemenkes...,ini yang bener yang mana beritanya kemenkes bi...,bener beritanya kemenkes bilang hmpv masuk gej...
46,Mana ada di China baik baik aja bos. Gak usah ...,mana ada di china baik baik aja bos gak usah d...,ada china aja bos gak d besarkan berita berita...
47,Virus Garuda enak pake ketoprak\n,virus garuda enak pake ketoprak,virus garuda enak pake ketoprak
48,Yailah bilang aja radang\n,yailah bilang aja radang,yailah bilang aja radang
49,"kalo disini namanya meriang, dah ada dari dulu\n",kalo disini namanya meriang dah ada dari dulu,kalo namanya meriang dah ada
50,"Rakyat indo harus kompak,kita tidak muw di bod...",rakyat indo harus kompakkita tidak muw di bodo...,rakyat indo kompakkita muw bodohi lagibukti ny...

In [86]:
from nltk.tokenize import word_tokenize
tokens = df['text_non_stopword'].tolist()

list_of_list = [word_tokenize(sentence) for sentence in tokens]
list_of_token = [word for sentence in list_of_list for word in sentence]

print(list_of_list)
print(list_of_token)

[['ramadhan', 'idulfitri', 'ada', 'aja', 'program', 'virus', 'ya'], ['penyakit', 'mematikan', 'media'], ['hahahah', 'berita', 'jancok'], ['si', 'media', 'bikin', 'ribet', 'bae', 'cina', 'aja', 'jg', 'ga', 'bikin', 'panik', 'orang', 'klo', 'cari', 'makan', 'yg', 'bener', 'dah', 'heran'], ['teman', 'gua', 'yg', 'tinggal', 'dichina', 'dsna', 'b', 'aja', 'indo', 'aja', 'yg', 'heboh', 'media', 'sosial', 'nya', 'yg', 'sengaja', 'bikin', 'heboh'], ['heran', 'heran', 'pas', 'natal', 'kemana', 'aja', 'giliran', 'ramadhan', 'idul', 'fitri', 'menghampiri', 'ada', 'aja', 'berita', 'sengaja', 'modus', 'rencana', 'orang', 'mengambil', 'keuntungan', 'corona', 'ladang', 'bisnis', 'oknum'], ['media', 'memperkeruh', 'kalo', 'emg', 'anggap', 'aja', 'udah', 'stop', 'hadeh'], ['media', 'emang', 'suka', 'nakutnakutin'], ['yg', 'nama', 'a', 'perubahan', 'cuaca', 'uda', 'sakit', 'imun', 'lemahjustru', 'liat', 'berita', 'kaya', 'gini', 'sakit', 'kefikiran', 'berusaha', 'byak', 'fikiran'], ['indo', 'langsung', 'lahan', 'bisnis'], ['malaysia', 'ga', 'ada', 'ga', 'ada', 'dngr', 'virus', 'temen', 'yg', 'china', 'nanya', 'bingung', 'kaatnya', 'ga', 'ada', 'tuh', 'ada', 'flu', 'krn', 'cuaca', 'mrk', 'skr', 'musim', 'dingin'], ['bodo', 'puasa', 'lebaran', 'ada', 'aja', 'ora', 'percaya'], ['beritanya', 'bikin', 'takut', 'cari', 'uang', 'enak', 'enak', 'ya', 'ada', 'virus', 'usaha', 'gue', 'mangkrak'], ['byk', 'yutube', 'org', 'org', 'indo', 'yg', 'cina', 'bilang', 'gak', 'segitunya', 'cina', 'awass', 'jgn', 'lg', 'vaksin'], ['video', 'orang', 'indo', 'china', 'aja', 'menjalani', 'kehidupan', 'bahakan', 'bingung', 'berita'], ['ya', 'elaah', 'yakali', 'gue', 'sakit', 'tenggorokan', 'gara', 'makan', 'rambutan', 'gue', 'panik', 'sik'], ['bisnis', 'menguntungkan', 'bisnis', 'menjual', 'ketakutan'], ['cina', 'cina', 'gk', 'bosen', 'cina', 'ngekspor', 'virus', 'mulu'], ['bodo', 'mudik', 'lebaran'], ['gw', 'bodo', 'min', 'gw', 'percaya', 'mati', 'kelaparan', 'virus'], ['ga', 'use', 'digoreng', 'dah', 'statement', 'nya', 'aja', 'kaya', 'flu'], ['virus', 'nyebarnya', 'media'], ['heduftttt'], ['hah', 'ada', 'trend', 'virus'], ['lumayan', 'proyek'], ['hati', 'hati', 'warga', 'depok'], ['nyari', 'modal', 'kemaren', 'nyoblos'], ['maaf', 'nanya', 'gmn', 'ya', 'ngempesin', 'perut', 'buncit', 'yg', 'efektif', 'ngrasa', 'nyaman', 'bngt'], ['dokter', 'meraup', 'pundi', 'pundi'], ['bacot'], ['yuhhuuu', 'menyala', 'abang', 'ku', 'sekolah', 'libur'], ['ada', 'vloger', 'yg', 'udh', 'pergi', 'china', 'membagikan', 'video', 'kondisi', 'disana', 'bersih', 'tenang', 'damai', 'aja', 'gak', 'sperti', 'yg', 'diberitakan'], ['udah', 'ketebak', 'arahnya', 'kemana', 'template', 'bgt', 'belajar', 'dr', 'kemarin'], ['wk', 'sodara', 'gue', 'yg', 'tkw', 'bilang', 'ga', 'ada', 'virus', 'temen', 'gue', 'yg', 'study', 'disana', 'ketawa', 'ngomong', 'bikin', 'virus', 'disana'], ['china', 'bawa', 'virus', 'mulu', 'heran', 'bawa', 'virus', 'kekayaan', 'gitu', 'jgn', 'penyakit', 'mulu'], ['virus', 'bisnis', 'yg', 'terstruktur', 'abaikan', 'gak', 'diberitain', 'tolak', 'plandemic'], ['percaya', 'mendingan', 'gw', 'ajak', 'debat', 'by', 'data', 'aj', 'mentri', 'kesehatan', 'yg', 'mah', 'yg', 'ktny', 'meninggal', 'covid', 'covid'], ['maaf', 'min', 'lg', 'bnyak', 'urussngua', 'dah', 'vaksin', 'msa', 'msih', 'mempan', 'virus'], ['puasa', 'virus', 'larang', 'orang', 'sholat', 'berjamaah', 'ya'], ['timbang', 'batuk', 'pilek', 'bilang', 'wabah', 'korupsi', 'tuh', 'wabah', 'terbesar', 'mematikan'], ['event', 'ramadhan', 'lebaran'], ['bentar', 'lg', 'lebaran', 'yajgn', 'dikasih', 'panggung', 'brita', 'kaya', 'gini'], ['fomo', 'nih', 'rame', 'penyakit', 'nya'], ['yg', 'travelling', 'tiati', 'pulang', 'indo'], ['bener', 'beritanya', 'kemenkes', 'bilang', 'hmpv', 'masuk', 'gejalanya', 'ringan'], ['ada', 'china', 'aja', 'bos', 'gak', 'd', 'besarkan', 'berita', 'berita', 'kayak', 'gini', 'dah'], ['virus', 'garuda', 'enak', 'pake', 'ketoprak'], ['yailah', 'bilang', 'aja', 'radang'], ['kalo', 'namanya', 'meriang', 'dah', 'ada'], ['rakyat', 'indo', 'kompakkita', 'muw', 'bodohi', 'lagibukti', 'nya', 'istri', 'sayatemen', 'vaksin', 'fisik', 'nya', 'lemah', 'banget', 'sakitin', 'mulutetangga', 'muw', 'oprasi', 'aja', 'kudu', 'muw', 'pasien', 'covidagar', 'proses', 'oprasi', 'nya', 'perlancarada', 'temen', 'kerja', 'yg', 'pas', 'vaksin', 'meninggal', 'rakyat', 'udah', 'susah', 'bikin', 'anarkismangkin', 'nya', 'kejahatan', 'karna', 'perkerjaan', 'yg', 'susah', 'nyabuat', 'makan', 'sehari']]
['ramadhan', 'idulfitri', 'ada', 'aja', 'program', 'virus', 'ya', 'penyakit', 'mematikan', 'media', 'hahahah', 'berita', 'jancok', 'si', 'media', 'bikin', 'ribet', 'bae', 'cina', 'aja', 'jg', 'ga', 'bikin', 'panik', 'orang', 'klo', 'cari', 'makan', 'yg', 'bener', 'dah', 'heran', 'teman', 'gua', 'yg', 'tinggal', 'dichina', 'dsna', 'b', 'aja', 'indo', 'aja', 'yg', 'heboh', 'media', 'sosial', 'nya', 'yg', 'sengaja', 'bikin', 'heboh', 'heran', 'heran', 'pas', 'natal', 'kemana', 'aja', 'giliran', 'ramadhan', 'idul', 'fitri', 'menghampiri', 'ada', 'aja', 'berita', 'sengaja', 'modus', 'rencana', 'orang', 'mengambil', 'keuntungan', 'corona', 'ladang', 'bisnis', 'oknum', 'media', 'memperkeruh', 'kalo', 'emg', 'anggap', 'aja', 'udah', 'stop', 'hadeh', 'media', 'emang', 'suka', 'nakutnakutin', 'yg', 'nama', 'a', 'perubahan', 'cuaca', 'uda', 'sakit', 'imun', 'lemahjustru', 'liat', 'berita', 'kaya', 'gini', 'sakit', 'kefikiran', 'berusaha', 'byak', 'fikiran', 'indo', 'langsung', 'lahan', 'bisnis', 'malaysia', 'ga', 'ada', 'ga', 'ada', 'dngr', 'virus', 'temen', 'yg', 'china', 'nanya', 'bingung', 'kaatnya', 'ga', 'ada', 'tuh', 'ada', 'flu', 'krn', 'cuaca', 'mrk', 'skr', 'musim', 'dingin', 'bodo', 'puasa', 'lebaran', 'ada', 'aja', 'ora', 'percaya', 'beritanya', 'bikin', 'takut', 'cari', 'uang', 'enak', 'enak', 'ya', 'ada', 'virus', 'usaha', 'gue', 'mangkrak', 'byk', 'yutube', 'org', 'org', 'indo', 'yg', 'cina', 'bilang', 'gak', 'segitunya', 'cina', 'awass', 'jgn', 'lg', 'vaksin', 'video', 'orang', 'indo', 'china', 'aja', 'menjalani', 'kehidupan', 'bahakan', 'bingung', 'berita', 'ya', 'elaah', 'yakali', 'gue', 'sakit', 'tenggorokan', 'gara', 'makan', 'rambutan', 'gue', 'panik', 'sik', 'bisnis', 'menguntungkan', 'bisnis', 'menjual', 'ketakutan', 'cina', 'cina', 'gk', 'bosen', 'cina', 'ngekspor', 'virus', 'mulu', 'bodo', 'mudik', 'lebaran', 'gw', 'bodo', 'min', 'gw', 'percaya', 'mati', 'kelaparan', 'virus', 'ga', 'use', 'digoreng', 'dah', 'statement', 'nya', 'aja', 'kaya', 'flu', 'virus', 'nyebarnya', 'media', 'heduftttt', 'hah', 'ada', 'trend', 'virus', 'lumayan', 'proyek', 'hati', 'hati', 'warga', 'depok', 'nyari', 'modal', 'kemaren', 'nyoblos', 'maaf', 'nanya', 'gmn', 'ya', 'ngempesin', 'perut', 'buncit', 'yg', 'efektif', 'ngrasa', 'nyaman', 'bngt', 'dokter', 'meraup', 'pundi', 'pundi', 'bacot', 'yuhhuuu', 'menyala', 'abang', 'ku', 'sekolah', 'libur', 'ada', 'vloger', 'yg', 'udh', 'pergi', 'china', 'membagikan', 'video', 'kondisi', 'disana', 'bersih', 'tenang', 'damai', 'aja', 'gak', 'sperti', 'yg', 'diberitakan', 'udah', 'ketebak', 'arahnya', 'kemana', 'template', 'bgt', 'belajar', 'dr', 'kemarin', 'wk', 'sodara', 'gue', 'yg', 'tkw', 'bilang', 'ga', 'ada', 'virus', 'temen', 'gue', 'yg', 'study', 'disana', 'ketawa', 'ngomong', 'bikin', 'virus', 'disana', 'china', 'bawa', 'virus', 'mulu', 'heran', 'bawa', 'virus', 'kekayaan', 'gitu', 'jgn', 'penyakit', 'mulu', 'virus', 'bisnis', 'yg', 'terstruktur', 'abaikan', 'gak', 'diberitain', 'tolak', 'plandemic', 'percaya', 'mendingan', 'gw', 'ajak', 'debat', 'by', 'data', 'aj', 'mentri', 'kesehatan', 'yg', 'mah', 'yg', 'ktny', 'meninggal', 'covid', 'covid', 'maaf', 'min', 'lg', 'bnyak', 'urussngua', 'dah', 'vaksin', 'msa', 'msih', 'mempan', 'virus', 'puasa', 'virus', 'larang', 'orang', 'sholat', 'berjamaah', 'ya', 'timbang', 'batuk', 'pilek', 'bilang', 'wabah', 'korupsi', 'tuh', 'wabah', 'terbesar', 'mematikan', 'event', 'ramadhan', 'lebaran', 'bentar', 'lg', 'lebaran', 'yajgn', 'dikasih', 'panggung', 'brita', 'kaya', 'gini', 'fomo', 'nih', 'rame', 'penyakit', 'nya', 'yg', 'travelling', 'tiati', 'pulang', 'indo', 'bener', 'beritanya', 'kemenkes', 'bilang', 'hmpv', 'masuk', 'gejalanya', 'ringan', 'ada', 'china', 'aja', 'bos', 'gak', 'd', 'besarkan', 'berita', 'berita', 'kayak', 'gini', 'dah', 'virus', 'garuda', 'enak', 'pake', 'ketoprak', 'yailah', 'bilang', 'aja', 'radang', 'kalo', 'namanya', 'meriang', 'dah', 'ada', 'rakyat', 'indo', 'kompakkita', 'muw', 'bodohi', 'lagibukti', 'nya', 'istri', 'sayatemen', 'vaksin', 'fisik', 'nya', 'lemah', 'banget', 'sakitin', 'mulutetangga', 'muw', 'oprasi', 'aja', 'kudu', 'muw', 'pasien', 'covidagar', 'proses', 'oprasi', 'nya', 'perlancarada', 'temen', 'kerja', 'yg', 'pas', 'vaksin', 'meninggal', 'rakyat', 'udah', 'susah', 'bikin', 'anarkismangkin', 'nya', 'kejahatan', 'karna', 'perkerjaan', 'yg', 'susah', 'nyabuat', 'makan', 'sehari']

In [89]:
word_counts = Counter(list_of_token)

for word, count in word_counts.most_common(100):
  print(f"{word}: {count}")

yg: 18
virus: 15
aja: 14
ada: 13
nya: 7
media: 6
berita: 6
bikin: 6
cina: 6
ga: 6
indo: 6
ya: 5
dah: 5
bisnis: 5
china: 5
gue: 5
bilang: 5
orang: 4
heran: 4
lebaran: 4
gak: 4
vaksin: 4
ramadhan: 3
penyakit: 3
makan: 3
udah: 3
sakit: 3
kaya: 3
gini: 3
temen: 3
bodo: 3
percaya: 3
enak: 3
lg: 3
mulu: 3
gw: 3
disana: 3
muw: 3
mematikan: 2
panik: 2
cari: 2
bener: 2
heboh: 2
sengaja: 2
pas: 2
kemana: 2
kalo: 2
cuaca: 2
nanya: 2
bingung: 2
tuh: 2
flu: 2
puasa: 2
beritanya: 2
org: 2
jgn: 2
video: 2
min: 2
hati: 2
maaf: 2
pundi: 2
bawa: 2
meninggal: 2
covid: 2
wabah: 2
rakyat: 2
oprasi: 2
susah: 2
idulfitri: 1
program: 1
hahahah: 1
jancok: 1
si: 1
ribet: 1
bae: 1
jg: 1
klo: 1
teman: 1
gua: 1
tinggal: 1
dichina: 1
dsna: 1
b: 1
sosial: 1
natal: 1
giliran: 1
idul: 1
fitri: 1
menghampiri: 1
modus: 1
rencana: 1
mengambil: 1
keuntungan: 1
corona: 1
ladang: 1
oknum: 1
memperkeruh: 1
emg: 1
anggap: 1
stop: 1

In [94]:
word_dict = {
    "ga":"tidak",
    "gak":"tidak",
    "kalo":"jika",
    "pelakor": "perebut laki orang",
    "bgt" : "sangat",
    "dgn": "dengan",
    "tp":"tapi",
    "sok":"sombong",
    "dr":"dari",
    "gw":"saya",
    'gua':'saya',
    'gue':'saya',
    "bener":"benar",
    "sy":"saya",
    'lo':'kamu',
    'lu':'kamu',
    'org':'orang',
    'n':'dan',
    'pake':'pakai',
    'jd':'jadi',
    'laki':'pria',
    'sm':'sama',
    'yg':'yang',
    'tau':'tahu',
    'd':'di',
    'tolol':'bodoh',
    'bego':'bodoh',
    'att':'atitut',
    'jgn':'jangan',
    'y':'ya',
    'tu':'tuh',
    'krn':'karena',
    'jaman':'zaman',
    'aj':'saja',
    'g':'tidak',
    'now':'sekarang',
    'biar':'agar',
    'geblek':'bodoh',
    'kmrn':'kemarin',
    'skrg':'sekarang',
    'apaoun':'apapun',
    'trus':'lalu',
    "yg":"yang",
    'bodo':'bodoh',
    'jg':'juga'
}

def fix_slang(sentence, word_dict):
  tokens = word_tokenize(sentence)
  fix_slangs = [word_dict.get(word, word) for word in tokens]
  return ' '.join(fix_slangs)

In [95]:
df['text_non_slang']  = df['text_non_stopword'] .apply(lambda x: fix_slang(x, word_dict))
df

,Instagram Comment Text,text_cleaned,text_non_stopword,text_non_slang
1,Setiap mau Ramadhan sama IdulFitri ada aja pro...,setiap mau ramadhan sama idulfitri ada aja pro...,ramadhan idulfitri ada aja program virus ya,ramadhan idulfitri ada aja program virus ya
2,Penyakit mematikan itu adalah Media\n,penyakit mematikan itu adalah media,penyakit mematikan media,penyakit mematikan media
3,Hahahah berita jancok ini\n,hahahah berita jancok ini,hahahah berita jancok,hahahah berita jancok
4,Apaan si media bikin ribet bae di cina biasa2 ...,apaan si media bikin ribet bae di cina biasa a...,si media bikin ribet bae cina aja jg ga bikin ...,si media bikin ribet bae cina aja juga tidak b...
5,Kata teman gua yg tinggal dichina dsna B aja c...,kata teman gua yg tinggal dichina dsna b aja c...,teman gua yg tinggal dichina dsna b aja indo a...,teman saya yang tinggal dichina dsna b aja ind...
6,Heran aku heran tadi pas natal dan tahun baru ...,heran aku heran tadi pas natal dan tahun baru ...,heran heran pas natal kemana aja giliran ramad...,heran heran pas natal kemana aja giliran ramad...
7,Media2 memperkeruh kalo emg di anggap biasa aj...,media memperkeruh kalo emg di anggap biasa aja...,media memperkeruh kalo emg anggap aja udah sto...,media memperkeruh jika emg anggap aja udah sto...
8,Media emang suka nakut-nakutin\n,media emang suka nakutnakutin,media emang suka nakutnakutin,media emang suka nakutnakutin
9,Yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda sakit imun lemah...,yang nama a perubahan cuaca uda sakit imun lem...
10,di indo langsung jadi lahan bisnis\n,di indo langsung jadi lahan bisnis,indo langsung lahan bisnis,indo langsung lahan bisnis
11,Kami di malaysia ga ada apa2 ga ada dngr kata2...,kami di malaysia ga ada apa ga ada dngr kata v...,malaysia ga ada ga ada dngr virus temen yg chi...,malaysia tidak ada tidak ada dngr virus temen ...
12,BODO AMAT !!! Setiap mau puasa setiap mau leba...,bodo amat setiap mau puasa setiap mau lebaran ...,bodo puasa lebaran ada aja ora percaya,bodoh puasa lebaran ada aja ora percaya
13,Beritanya jangan yang bikin takut saya lagi ca...,beritanya jangan yang bikin takut saya lagi ca...,beritanya bikin takut cari uang enak enak ya a...,beritanya bikin takut cari uang enak enak ya a...
14,Byk di yutube org org indo yg di cina bilang g...,byk di yutube org org indo yg di cina bilang g...,byk yutube org org indo yg cina bilang gak seg...,byk yutube orang orang indo yang cina bilang t...
15,Apaan banyak video orang indo di China pada bi...,apaan banyak video orang indo di china pada bi...,video orang indo china aja menjalani kehidupan...,video orang indo china aja menjalani kehidupan...
16,"ya elaah, yakali gue sakit tenggorokan gara2 b...",ya elaah yakali gue sakit tenggorokan gara ban...,ya elaah yakali gue sakit tenggorokan gara mak...,ya elaah yakali saya sakit tenggorokan gara ma...
17,Bisnis yang menguntungkan adalah Bisnis yang m...,bisnis yang menguntungkan adalah bisnis yang m...,bisnis menguntungkan bisnis menjual ketakutan,bisnis menguntungkan bisnis menjual ketakutan
18,Cina lagi cina lagi GK bosen apa cina ngekspor...,cina lagi cina lagi gk bosen apa cina ngekspor...,cina cina gk bosen cina ngekspor virus mulu,cina cina gk bosen cina ngekspor virus mulu
19,Bodo amat yang penting saya tetap mudik lebara...,bodo amat yang penting saya tetap mudik lebaran,bodo mudik lebaran,bodoh mudik lebaran
20,GW BODO AMAT MIN.. GW LEBIH PERCAYA MATI KAREN...,gw bodo amat min gw lebih percaya mati karena ...,gw bodo min gw percaya mati kelaparan virus,saya bodoh min saya percaya mati kelaparan virus
21,"Ga use digoreng2 dah, statement nya aja sama k...",ga use digoreng dah statement nya aja sama kay...,ga use digoreng dah statement nya aja kaya flu,tidak use digoreng dah statement nya aja kaya flu
22,Virus sekarang nyebarnya melalui media\n,virus sekarang nyebarnya melalui media,virus nyebarnya media,virus nyebarnya media
23,Apalagi ini... Heduftttt\n,apalagi ini heduftttt,heduftttt,heduftttt
24,Hah ada trend virus lagi\n,hah ada trend virus lagi,hah ada trend virus,hah ada trend virus
25,lumayan proyek\n,lumayan proyek,lumayan proyek,lumayan proyek
26,Hati hati warga depok\n,hati hati warga depok,hati hati warga depok,hati hati warga depok
27,Nyari balik modal kemaren nyoblos..\n,nyari balik modal kemaren nyoblos,nyari modal kemaren nyoblos,nyari modal kemaren nyoblos
28,"Maaf ikut nanya, gmn ya cara ngempesin perut b...",maaf ikut nanya gmn ya cara ngempesin perut bu...,maaf nanya gmn ya ngempesin perut buncit yg ef...,maaf nanya gmn ya ngempesin perut buncit yang ...
29,SAATNYA DOKTER KEMBALI MERAUP PUNDI PUNDI\n,saatnya dokter kembali meraup pundi pundi,dokter meraup pundi pundi,dokter meraup pundi pundi
30,Bacot\n,bacot,bacot,bacot
31,Yuhhuuu menyala Abang ku sekolah libur lagi 3t...,yuhhuuu menyala abang ku sekolah libur lagi tahun,yuhhuuu menyala abang ku sekolah libur,yuhhuuu menyala abang ku sekolah libur
32,Ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi china membagikan video...,ada vloger yang udh pergi china membagikan vid...
33,"Udah ketebak kan arahnya kemana template bgt, ...",udah ketebak kan arahnya kemana template bgt b...,udah ketebak arahnya kemana template bgt belaj...,udah ketebak arahnya kemana template sangat be...
34,"""Wkwk sodara gue yg jadi TKW sana bilang ga ad...",wk sodara gue yg jadi tkw sana bilang ga ada v...,wk sodara gue yg tkw bilang ga ada virus temen...,wk sodara saya yang tkw bilang tidak ada virus...
35,"Di china bawa virus mulu heran, bawa virus kek...",di china bawa virus mulu heran bawa virus keka...,china bawa virus mulu heran bawa virus kekayaa...,china bawa virus mulu heran bawa virus kekayaa...
36,Virus Bisnis yg terstruktur. Abaikan Dan gak u...,virus bisnis yg terstruktur abaikan dan gak us...,virus bisnis yg terstruktur abaikan gak diberi...,virus bisnis yang terstruktur abaikan tidak di...
37,Percaya? Mendingan gw ajak debat by data aj sa...,percaya mendingan gw ajak debat by data aj sam...,percaya mendingan gw ajak debat by data aj men...,percaya mendingan saya ajak debat by data saja...
38,"Maaf min lg bnyak urussn,gua dulu dah vaksin j...",maaf min lg bnyak urussngua dulu dah vaksin ju...,maaf min lg bnyak urussngua dah vaksin msa msi...,maaf min lg bnyak urussngua dah vaksin msa msi...
39,"Tiap mau puasa kok virus baru, mau larang oran...",tiap mau puasa kok virus baru mau larang orang...,puasa virus larang orang sholat berjamaah ya,puasa virus larang orang sholat berjamaah ya
40,Timbang batuk pilek di bilang wabah.. KORUPSI ...,timbang batuk pilek di bilang wabah korupsi tu...,timbang batuk pilek bilang wabah korupsi tuh w...,timbang batuk pilek bilang wabah korupsi tuh w...
41,Event apa lagi ini mau dekat ramadhan dan leba...,event apa lagi ini mau dekat ramadhan dan lebaran,event ramadhan lebaran,event ramadhan lebaran
42,"Bentar LG lebaran ya,jgn dikasih panggung brit...",bentar lg lebaran yajgn dikasih panggung brita...,bentar lg lebaran yajgn dikasih panggung brita...,bentar lg lebaran yajgn dikasih panggung brita...
43,"banyak fomo nih, jadi rame kan penyakit nya.\n",banyak fomo nih jadi rame kan penyakit nya,fomo nih rame penyakit nya,fomo nih rame penyakit nya
44,Yg lagi travelling tiati pulang ke Indo\n,yg lagi travelling tiati pulang ke indo,yg travelling tiati pulang indo,yang travelling tiati pulang indo
45,Ini yang bener yang mana beritanya??? Kemenkes...,ini yang bener yang mana beritanya kemenkes bi...,bener beritanya kemenkes bilang hmpv masuk gej...,benar beritanya kemenkes bilang hmpv masuk gej...
46,Mana ada di China baik baik aja bos. Gak usah ...,mana ada di china baik baik aja bos gak usah d...,ada china aja bos gak d besarkan berita berita...,ada china aja bos tidak di besarkan berita ber...
47,Virus Garuda enak pake ketoprak\n,virus garuda enak pake ketoprak,virus garuda enak pake ketoprak,virus garuda enak pakai ketoprak
48,Yailah bilang aja radang\n,yailah bilang aja radang,yailah bilang aja radang,yailah bilang aja radang
49,"kalo disini namanya meriang, dah ada dari dulu\n",kalo disini namanya meriang dah ada dari dulu,kalo namanya meriang dah ada,jika namanya meriang dah ada
50,"Rakyat indo harus kompak,kita tidak muw di bod...",rakyat indo harus kompakkita tidak muw di bodo...,rakyat indo kompakkita muw bodohi lagibukti ny...,rakyat indo kompakkita muw bodohi lagibukti ny...

Bersihlah semua data kita dari Huruf besar kecilnya, tanda baca, stopword dan slang. Baru bisa kita coba cek sentimennya dengan 2 Metode sebelumnya.

## Metode Naive Bayes Komentar Asli

In [98]:
df['count'] = df['text_non_slang'].apply(lambda x: sentiment_counts(x, positive_words, negative_words))
df.head(10)

,Instagram Comment Text,text_cleaned,text_non_stopword,text_non_slang,count
1,Setiap mau Ramadhan sama IdulFitri ada aja pro...,setiap mau ramadhan sama idulfitri ada aja pro...,ramadhan idulfitri ada aja program virus ya,ramadhan idulfitri ada aja program virus ya,-1
2,Penyakit mematikan itu adalah Media\n,penyakit mematikan itu adalah media,penyakit mematikan media,penyakit mematikan media,-1
3,Hahahah berita jancok ini\n,hahahah berita jancok ini,hahahah berita jancok,hahahah berita jancok,0
4,Apaan si media bikin ribet bae di cina biasa2 ...,apaan si media bikin ribet bae di cina biasa a...,si media bikin ribet bae cina aja jg ga bikin ...,si media bikin ribet bae cina aja juga tidak b...,-1
5,Kata teman gua yg tinggal dichina dsna B aja c...,kata teman gua yg tinggal dichina dsna b aja c...,teman gua yg tinggal dichina dsna b aja indo a...,teman saya yang tinggal dichina dsna b aja ind...,0
6,Heran aku heran tadi pas natal dan tahun baru ...,heran aku heran tadi pas natal dan tahun baru ...,heran heran pas natal kemana aja giliran ramad...,heran heran pas natal kemana aja giliran ramad...,-2
7,Media2 memperkeruh kalo emg di anggap biasa aj...,media memperkeruh kalo emg di anggap biasa aja...,media memperkeruh kalo emg anggap aja udah sto...,media memperkeruh jika emg anggap aja udah sto...,0
8,Media emang suka nakut-nakutin\n,media emang suka nakutnakutin,media emang suka nakutnakutin,media emang suka nakutnakutin,0
9,Yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda sakit imun lemah...,yang nama a perubahan cuaca uda sakit imun lem...,-1
10,di indo langsung jadi lahan bisnis\n,di indo langsung jadi lahan bisnis,indo langsung lahan bisnis,indo langsung lahan bisnis,0

In [99]:
df['hasil sentimen'] = df['count'].apply(sentimen)
df

,Instagram Comment Text,text_cleaned,text_non_stopword,text_non_slang,count,hasil sentimen
1,Setiap mau Ramadhan sama IdulFitri ada aja pro...,setiap mau ramadhan sama idulfitri ada aja pro...,ramadhan idulfitri ada aja program virus ya,ramadhan idulfitri ada aja program virus ya,-1,negatif
2,Penyakit mematikan itu adalah Media\n,penyakit mematikan itu adalah media,penyakit mematikan media,penyakit mematikan media,-1,negatif
3,Hahahah berita jancok ini\n,hahahah berita jancok ini,hahahah berita jancok,hahahah berita jancok,0,netral
4,Apaan si media bikin ribet bae di cina biasa2 ...,apaan si media bikin ribet bae di cina biasa a...,si media bikin ribet bae cina aja jg ga bikin ...,si media bikin ribet bae cina aja juga tidak b...,-1,negatif
5,Kata teman gua yg tinggal dichina dsna B aja c...,kata teman gua yg tinggal dichina dsna b aja c...,teman gua yg tinggal dichina dsna b aja indo a...,teman saya yang tinggal dichina dsna b aja ind...,0,netral
6,Heran aku heran tadi pas natal dan tahun baru ...,heran aku heran tadi pas natal dan tahun baru ...,heran heran pas natal kemana aja giliran ramad...,heran heran pas natal kemana aja giliran ramad...,-2,negatif
7,Media2 memperkeruh kalo emg di anggap biasa aj...,media memperkeruh kalo emg di anggap biasa aja...,media memperkeruh kalo emg anggap aja udah sto...,media memperkeruh jika emg anggap aja udah sto...,0,netral
8,Media emang suka nakut-nakutin\n,media emang suka nakutnakutin,media emang suka nakutnakutin,media emang suka nakutnakutin,0,netral
9,Yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda sakit imun lemah...,yang nama a perubahan cuaca uda sakit imun lem...,-1,negatif
10,di indo langsung jadi lahan bisnis\n,di indo langsung jadi lahan bisnis,indo langsung lahan bisnis,indo langsung lahan bisnis,0,netral
11,Kami di malaysia ga ada apa2 ga ada dngr kata2...,kami di malaysia ga ada apa ga ada dngr kata v...,malaysia ga ada ga ada dngr virus temen yg chi...,malaysia tidak ada tidak ada dngr virus temen ...,-2,negatif
12,BODO AMAT !!! Setiap mau puasa setiap mau leba...,bodo amat setiap mau puasa setiap mau lebaran ...,bodo puasa lebaran ada aja ora percaya,bodoh puasa lebaran ada aja ora percaya,0,netral
13,Beritanya jangan yang bikin takut saya lagi ca...,beritanya jangan yang bikin takut saya lagi ca...,beritanya bikin takut cari uang enak enak ya a...,beritanya bikin takut cari uang enak enak ya a...,0,netral
14,Byk di yutube org org indo yg di cina bilang g...,byk di yutube org org indo yg di cina bilang g...,byk yutube org org indo yg cina bilang gak seg...,byk yutube orang orang indo yang cina bilang t...,0,netral
15,Apaan banyak video orang indo di China pada bi...,apaan banyak video orang indo di china pada bi...,video orang indo china aja menjalani kehidupan...,video orang indo china aja menjalani kehidupan...,-1,negatif
16,"ya elaah, yakali gue sakit tenggorokan gara2 b...",ya elaah yakali gue sakit tenggorokan gara ban...,ya elaah yakali gue sakit tenggorokan gara mak...,ya elaah yakali saya sakit tenggorokan gara ma...,-1,negatif
17,Bisnis yang menguntungkan adalah Bisnis yang m...,bisnis yang menguntungkan adalah bisnis yang m...,bisnis menguntungkan bisnis menjual ketakutan,bisnis menguntungkan bisnis menjual ketakutan,0,netral
18,Cina lagi cina lagi GK bosen apa cina ngekspor...,cina lagi cina lagi gk bosen apa cina ngekspor...,cina cina gk bosen cina ngekspor virus mulu,cina cina gk bosen cina ngekspor virus mulu,-1,negatif
19,Bodo amat yang penting saya tetap mudik lebara...,bodo amat yang penting saya tetap mudik lebaran,bodo mudik lebaran,bodoh mudik lebaran,-1,negatif
20,GW BODO AMAT MIN.. GW LEBIH PERCAYA MATI KAREN...,gw bodo amat min gw lebih percaya mati karena ...,gw bodo min gw percaya mati kelaparan virus,saya bodoh min saya percaya mati kelaparan virus,-2,negatif
21,"Ga use digoreng2 dah, statement nya aja sama k...",ga use digoreng dah statement nya aja sama kay...,ga use digoreng dah statement nya aja kaya flu,tidak use digoreng dah statement nya aja kaya flu,0,netral
22,Virus sekarang nyebarnya melalui media\n,virus sekarang nyebarnya melalui media,virus nyebarnya media,virus nyebarnya media,-1,negatif
23,Apalagi ini... Heduftttt\n,apalagi ini heduftttt,heduftttt,heduftttt,0,netral
24,Hah ada trend virus lagi\n,hah ada trend virus lagi,hah ada trend virus,hah ada trend virus,-1,negatif
25,lumayan proyek\n,lumayan proyek,lumayan proyek,lumayan proyek,0,netral
26,Hati hati warga depok\n,hati hati warga depok,hati hati warga depok,hati hati warga depok,0,netral
27,Nyari balik modal kemaren nyoblos..\n,nyari balik modal kemaren nyoblos,nyari modal kemaren nyoblos,nyari modal kemaren nyoblos,0,netral
28,"Maaf ikut nanya, gmn ya cara ngempesin perut b...",maaf ikut nanya gmn ya cara ngempesin perut bu...,maaf nanya gmn ya ngempesin perut buncit yg ef...,maaf nanya gmn ya ngempesin perut buncit yang ...,3,positif
29,SAATNYA DOKTER KEMBALI MERAUP PUNDI PUNDI\n,saatnya dokter kembali meraup pundi pundi,dokter meraup pundi pundi,dokter meraup pundi pundi,0,netral
30,Bacot\n,bacot,bacot,bacot,0,netral
31,Yuhhuuu menyala Abang ku sekolah libur lagi 3t...,yuhhuuu menyala abang ku sekolah libur lagi tahun,yuhhuuu menyala abang ku sekolah libur,yuhhuuu menyala abang ku sekolah libur,0,netral
32,Ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi china membagikan video...,ada vloger yang udh pergi china membagikan vid...,0,netral
33,"Udah ketebak kan arahnya kemana template bgt, ...",udah ketebak kan arahnya kemana template bgt b...,udah ketebak arahnya kemana template bgt belaj...,udah ketebak arahnya kemana template sangat be...,1,positif
34,"""Wkwk sodara gue yg jadi TKW sana bilang ga ad...",wk sodara gue yg jadi tkw sana bilang ga ada v...,wk sodara gue yg tkw bilang ga ada virus temen...,wk sodara saya yang tkw bilang tidak ada virus...,-2,negatif
35,"Di china bawa virus mulu heran, bawa virus kek...",di china bawa virus mulu heran bawa virus keka...,china bawa virus mulu heran bawa virus kekayaa...,china bawa virus mulu heran bawa virus kekayaa...,-4,negatif
36,Virus Bisnis yg terstruktur. Abaikan Dan gak u...,virus bisnis yg terstruktur abaikan dan gak us...,virus bisnis yg terstruktur abaikan gak diberi...,virus bisnis yang terstruktur abaikan tidak di...,0,netral
37,Percaya? Mendingan gw ajak debat by data aj sa...,percaya mendingan gw ajak debat by data aj sam...,percaya mendingan gw ajak debat by data aj men...,percaya mendingan saya ajak debat by data saja...,0,netral
38,"Maaf min lg bnyak urussn,gua dulu dah vaksin j...",maaf min lg bnyak urussngua dulu dah vaksin ju...,maaf min lg bnyak urussngua dah vaksin msa msi...,maaf min lg bnyak urussngua dah vaksin msa msi...,0,netral
39,"Tiap mau puasa kok virus baru, mau larang oran...",tiap mau puasa kok virus baru mau larang orang...,puasa virus larang orang sholat berjamaah ya,puasa virus larang orang sholat berjamaah ya,-1,negatif
40,Timbang batuk pilek di bilang wabah.. KORUPSI ...,timbang batuk pilek di bilang wabah korupsi tu...,timbang batuk pilek bilang wabah korupsi tuh w...,timbang batuk pilek bilang wabah korupsi tuh w...,-3,negatif
41,Event apa lagi ini mau dekat ramadhan dan leba...,event apa lagi ini mau dekat ramadhan dan lebaran,event ramadhan lebaran,event ramadhan lebaran,0,netral
42,"Bentar LG lebaran ya,jgn dikasih panggung brit...",bentar lg lebaran yajgn dikasih panggung brita...,bentar lg lebaran yajgn dikasih panggung brita...,bentar lg lebaran yajgn dikasih panggung brita...,0,netral
43,"banyak fomo nih, jadi rame kan penyakit nya.\n",banyak fomo nih jadi rame kan penyakit nya,fomo nih rame penyakit nya,fomo nih rame penyakit nya,-1,negatif
44,Yg lagi travelling tiati pulang ke Indo\n,yg lagi travelling tiati pulang ke indo,yg travelling tiati pulang indo,yang travelling tiati pulang indo,0,netral
45,Ini yang bener yang mana beritanya??? Kemenkes...,ini yang bener yang mana beritanya kemenkes bi...,bener beritanya kemenkes bilang hmpv masuk gej...,benar beritanya kemenkes bilang hmpv masuk gej...,1,positif
46,Mana ada di China baik baik aja bos. Gak usah ...,mana ada di china baik baik aja bos gak usah d...,ada china aja bos gak d besarkan berita berita...,ada china aja bos tidak di besarkan berita ber...,0,netral
47,Virus Garuda enak pake ketoprak\n,virus garuda enak pake ketoprak,virus garuda enak pake ketoprak,virus garuda enak pakai ketoprak,0,netral
48,Yailah bilang aja radang\n,yailah bilang aja radang,yailah bilang aja radang,yailah bilang aja radang,-1,negatif
49,"kalo disini namanya meriang, dah ada dari dulu\n",kalo disini namanya meriang dah ada dari dulu,kalo namanya meriang dah ada,jika namanya meriang dah ada,0,netral
50,"Rakyat indo harus kompak,kita tidak muw di bod...",rakyat indo harus kompakkita tidak muw di bodo...,rakyat indo kompakkita muw bodohi lagibukti ny...,rakyat indo kompakkita muw bodohi lagibukti ny...,-3,negatif

In [100]:
df['hasil sentimen'].value_counts()

hasil sentimen
netral     27
negatif    20
positif     3
Name: count, dtype: int64

Dengan Naive Bayes, Sentimen terbanyak di data kita adalah sentimen Netral, yang diikuti sentimen Negatif dan terakhir di Positif.

## Metode Lexicon Komentar Asli

In [101]:
df['lexicon_sentiment'] = df['text_non_slang'].apply(lambda x: sentiment_counts_lex(x, positive_lex, negative_lex, stemmer))
df

,Instagram Comment Text,text_cleaned,text_non_stopword,text_non_slang,count,hasil sentimen,lexicon_sentiment
1,Setiap mau Ramadhan sama IdulFitri ada aja pro...,setiap mau ramadhan sama idulfitri ada aja pro...,ramadhan idulfitri ada aja program virus ya,ramadhan idulfitri ada aja program virus ya,-1,negatif,negative
2,Penyakit mematikan itu adalah Media\n,penyakit mematikan itu adalah media,penyakit mematikan media,penyakit mematikan media,-1,negatif,negative
3,Hahahah berita jancok ini\n,hahahah berita jancok ini,hahahah berita jancok,hahahah berita jancok,0,netral,neutral
4,Apaan si media bikin ribet bae di cina biasa2 ...,apaan si media bikin ribet bae di cina biasa a...,si media bikin ribet bae cina aja jg ga bikin ...,si media bikin ribet bae cina aja juga tidak b...,-1,negatif,negative
5,Kata teman gua yg tinggal dichina dsna B aja c...,kata teman gua yg tinggal dichina dsna b aja c...,teman gua yg tinggal dichina dsna b aja indo a...,teman saya yang tinggal dichina dsna b aja ind...,0,netral,positive
6,Heran aku heran tadi pas natal dan tahun baru ...,heran aku heran tadi pas natal dan tahun baru ...,heran heran pas natal kemana aja giliran ramad...,heran heran pas natal kemana aja giliran ramad...,-2,negatif,positive
7,Media2 memperkeruh kalo emg di anggap biasa aj...,media memperkeruh kalo emg di anggap biasa aja...,media memperkeruh kalo emg anggap aja udah sto...,media memperkeruh jika emg anggap aja udah sto...,0,netral,neutral
8,Media emang suka nakut-nakutin\n,media emang suka nakutnakutin,media emang suka nakutnakutin,media emang suka nakutnakutin,0,netral,neutral
9,Yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda pasti sakit apa ...,yg nama a perubahan cuaca uda sakit imun lemah...,yang nama a perubahan cuaca uda sakit imun lem...,-1,negatif,negative
10,di indo langsung jadi lahan bisnis\n,di indo langsung jadi lahan bisnis,indo langsung lahan bisnis,indo langsung lahan bisnis,0,netral,neutral
11,Kami di malaysia ga ada apa2 ga ada dngr kata2...,kami di malaysia ga ada apa ga ada dngr kata v...,malaysia ga ada ga ada dngr virus temen yg chi...,malaysia tidak ada tidak ada dngr virus temen ...,-2,negatif,negative
12,BODO AMAT !!! Setiap mau puasa setiap mau leba...,bodo amat setiap mau puasa setiap mau lebaran ...,bodo puasa lebaran ada aja ora percaya,bodoh puasa lebaran ada aja ora percaya,0,netral,negative
13,Beritanya jangan yang bikin takut saya lagi ca...,beritanya jangan yang bikin takut saya lagi ca...,beritanya bikin takut cari uang enak enak ya a...,beritanya bikin takut cari uang enak enak ya a...,0,netral,neutral
14,Byk di yutube org org indo yg di cina bilang g...,byk di yutube org org indo yg di cina bilang g...,byk yutube org org indo yg cina bilang gak seg...,byk yutube orang orang indo yang cina bilang t...,0,netral,negative
15,Apaan banyak video orang indo di China pada bi...,apaan banyak video orang indo di china pada bi...,video orang indo china aja menjalani kehidupan...,video orang indo china aja menjalani kehidupan...,-1,negatif,negative
16,"ya elaah, yakali gue sakit tenggorokan gara2 b...",ya elaah yakali gue sakit tenggorokan gara ban...,ya elaah yakali gue sakit tenggorokan gara mak...,ya elaah yakali saya sakit tenggorokan gara ma...,-1,negatif,negative
17,Bisnis yang menguntungkan adalah Bisnis yang m...,bisnis yang menguntungkan adalah bisnis yang m...,bisnis menguntungkan bisnis menjual ketakutan,bisnis menguntungkan bisnis menjual ketakutan,0,netral,neutral
18,Cina lagi cina lagi GK bosen apa cina ngekspor...,cina lagi cina lagi gk bosen apa cina ngekspor...,cina cina gk bosen cina ngekspor virus mulu,cina cina gk bosen cina ngekspor virus mulu,-1,negatif,negative
19,Bodo amat yang penting saya tetap mudik lebara...,bodo amat yang penting saya tetap mudik lebaran,bodo mudik lebaran,bodoh mudik lebaran,-1,negatif,negative
20,GW BODO AMAT MIN.. GW LEBIH PERCAYA MATI KAREN...,gw bodo amat min gw lebih percaya mati karena ...,gw bodo min gw percaya mati kelaparan virus,saya bodoh min saya percaya mati kelaparan virus,-2,negatif,negative
21,"Ga use digoreng2 dah, statement nya aja sama k...",ga use digoreng dah statement nya aja sama kay...,ga use digoreng dah statement nya aja kaya flu,tidak use digoreng dah statement nya aja kaya flu,0,netral,negative
22,Virus sekarang nyebarnya melalui media\n,virus sekarang nyebarnya melalui media,virus nyebarnya media,virus nyebarnya media,-1,negatif,negative
23,Apalagi ini... Heduftttt\n,apalagi ini heduftttt,heduftttt,heduftttt,0,netral,neutral
24,Hah ada trend virus lagi\n,hah ada trend virus lagi,hah ada trend virus,hah ada trend virus,-1,negatif,negative
25,lumayan proyek\n,lumayan proyek,lumayan proyek,lumayan proyek,0,netral,positive
26,Hati hati warga depok\n,hati hati warga depok,hati hati warga depok,hati hati warga depok,0,netral,positive
27,Nyari balik modal kemaren nyoblos..\n,nyari balik modal kemaren nyoblos,nyari modal kemaren nyoblos,nyari modal kemaren nyoblos,0,netral,neutral
28,"Maaf ikut nanya, gmn ya cara ngempesin perut b...",maaf ikut nanya gmn ya cara ngempesin perut bu...,maaf nanya gmn ya ngempesin perut buncit yg ef...,maaf nanya gmn ya ngempesin perut buncit yang ...,3,positif,positive
29,SAATNYA DOKTER KEMBALI MERAUP PUNDI PUNDI\n,saatnya dokter kembali meraup pundi pundi,dokter meraup pundi pundi,dokter meraup pundi pundi,0,netral,neutral
30,Bacot\n,bacot,bacot,bacot,0,netral,neutral
31,Yuhhuuu menyala Abang ku sekolah libur lagi 3t...,yuhhuuu menyala abang ku sekolah libur lagi tahun,yuhhuuu menyala abang ku sekolah libur,yuhhuuu menyala abang ku sekolah libur,0,netral,neutral
32,Ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi ke china dan dia memba...,ada vloger yg udh pergi china membagikan video...,ada vloger yang udh pergi china membagikan vid...,0,netral,positive
33,"Udah ketebak kan arahnya kemana template bgt, ...",udah ketebak kan arahnya kemana template bgt b...,udah ketebak arahnya kemana template bgt belaj...,udah ketebak arahnya kemana template sangat be...,1,positif,neutral
34,"""Wkwk sodara gue yg jadi TKW sana bilang ga ad...",wk sodara gue yg jadi tkw sana bilang ga ada v...,wk sodara gue yg tkw bilang ga ada virus temen...,wk sodara saya yang tkw bilang tidak ada virus...,-2,negatif,negative
35,"Di china bawa virus mulu heran, bawa virus kek...",di china bawa virus mulu heran bawa virus keka...,china bawa virus mulu heran bawa virus kekayaa...,china bawa virus mulu heran bawa virus kekayaa...,-4,negatif,negative
36,Virus Bisnis yg terstruktur. Abaikan Dan gak u...,virus bisnis yg terstruktur abaikan dan gak us...,virus bisnis yg terstruktur abaikan gak diberi...,virus bisnis yang terstruktur abaikan tidak di...,0,netral,negative
37,Percaya? Mendingan gw ajak debat by data aj sa...,percaya mendingan gw ajak debat by data aj sam...,percaya mendingan gw ajak debat by data aj men...,percaya mendingan saya ajak debat by data saja...,0,netral,positive
38,"Maaf min lg bnyak urussn,gua dulu dah vaksin j...",maaf min lg bnyak urussngua dulu dah vaksin ju...,maaf min lg bnyak urussngua dah vaksin msa msi...,maaf min lg bnyak urussngua dah vaksin msa msi...,0,netral,neutral
39,"Tiap mau puasa kok virus baru, mau larang oran...",tiap mau puasa kok virus baru mau larang orang...,puasa virus larang orang sholat berjamaah ya,puasa virus larang orang sholat berjamaah ya,-1,negatif,negative
40,Timbang batuk pilek di bilang wabah.. KORUPSI ...,timbang batuk pilek di bilang wabah korupsi tu...,timbang batuk pilek bilang wabah korupsi tuh w...,timbang batuk pilek bilang wabah korupsi tuh w...,-3,negatif,negative
41,Event apa lagi ini mau dekat ramadhan dan leba...,event apa lagi ini mau dekat ramadhan dan lebaran,event ramadhan lebaran,event ramadhan lebaran,0,netral,neutral
42,"Bentar LG lebaran ya,jgn dikasih panggung brit...",bentar lg lebaran yajgn dikasih panggung brita...,bentar lg lebaran yajgn dikasih panggung brita...,bentar lg lebaran yajgn dikasih panggung brita...,0,netral,positive
43,"banyak fomo nih, jadi rame kan penyakit nya.\n",banyak fomo nih jadi rame kan penyakit nya,fomo nih rame penyakit nya,fomo nih rame penyakit nya,-1,negatif,negative
44,Yg lagi travelling tiati pulang ke Indo\n,yg lagi travelling tiati pulang ke indo,yg travelling tiati pulang indo,yang travelling tiati pulang indo,0,netral,neutral
45,Ini yang bener yang mana beritanya??? Kemenkes...,ini yang bener yang mana beritanya kemenkes bi...,bener beritanya kemenkes bilang hmpv masuk gej...,benar beritanya kemenkes bilang hmpv masuk gej...,1,positif,positive
46,Mana ada di China baik baik aja bos. Gak usah ...,mana ada di china baik baik aja bos gak usah d...,ada china aja bos gak d besarkan berita berita...,ada china aja bos tidak di besarkan berita ber...,0,netral,neutral
47,Virus Garuda enak pake ketoprak\n,virus garuda enak pake ketoprak,virus garuda enak pake ketoprak,virus garuda enak pakai ketoprak,0,netral,neutral
48,Yailah bilang aja radang\n,yailah bilang aja radang,yailah bilang aja radang,yailah bilang aja radang,-1,negatif,neutral
49,"kalo disini namanya meriang, dah ada dari dulu\n",kalo disini namanya meriang dah ada dari dulu,kalo namanya meriang dah ada,jika namanya meriang dah ada,0,netral,neutral
50,"Rakyat indo harus kompak,kita tidak muw di bod...",rakyat indo harus kompakkita tidak muw di bodo...,rakyat indo kompakkita muw bodohi lagibukti ny...,rakyat indo kompakkita muw bodohi lagibukti ny...,-3,negatif,negative

In [102]:
df['lexicon_sentiment'].value_counts()

lexicon_sentiment
negative    22
neutral     19
positive     9
Name: count, dtype: int64

Ternyata berbeda dengan hasil sebelumnya, Lexicon memberikan pernyataan bahwa Sentimen Negatif lebih banyak daripada Netral dan tetap Positif ada di peringkat terakhir.

## Hasil Penelitian Penggunaan Metode Naive Bayes dan Lexicon Pada Komentar IG Indozone ID



Komentar Pada IG Indozone ID pada dasarnya tergantung berita pada postingannya. dan jika dilihat langsung dari komentarnya, Metode Lexicon dapat menilai dengan lebih baik dibandingkan Naive Bayes jika berhubungan dengan sentimen yang terbatas.

In [103]:
kolom_terpilih = ['Instagram Comment Text', 'hasil sentimen', 'lexicon_sentiment']
df_ = df[kolom_terpilih].copy()
df_

,Instagram Comment Text,hasil sentimen,lexicon_sentiment
1,Setiap mau Ramadhan sama IdulFitri ada aja pro...,negatif,negative
2,Penyakit mematikan itu adalah Media\n,negatif,negative
3,Hahahah berita jancok ini\n,netral,neutral
4,Apaan si media bikin ribet bae di cina biasa2 ...,negatif,negative
5,Kata teman gua yg tinggal dichina dsna B aja c...,netral,positive
6,Heran aku heran tadi pas natal dan tahun baru ...,negatif,positive
7,Media2 memperkeruh kalo emg di anggap biasa aj...,netral,neutral
8,Media emang suka nakut-nakutin\n,netral,neutral
9,Yg nama a perubahan cuaca uda pasti sakit apa ...,negatif,negative
10,di indo langsung jadi lahan bisnis\n,netral,neutral
11,Kami di malaysia ga ada apa2 ga ada dngr kata2...,negatif,negative
12,BODO AMAT !!! Setiap mau puasa setiap mau leba...,netral,negative
13,Beritanya jangan yang bikin takut saya lagi ca...,netral,neutral
14,Byk di yutube org org indo yg di cina bilang g...,netral,negative
15,Apaan banyak video orang indo di China pada bi...,negatif,negative
16,"ya elaah, yakali gue sakit tenggorokan gara2 b...",negatif,negative
17,Bisnis yang menguntungkan adalah Bisnis yang m...,netral,neutral
18,Cina lagi cina lagi GK bosen apa cina ngekspor...,negatif,negative
19,Bodo amat yang penting saya tetap mudik lebara...,negatif,negative
20,GW BODO AMAT MIN.. GW LEBIH PERCAYA MATI KAREN...,negatif,negative
21,"Ga use digoreng2 dah, statement nya aja sama k...",netral,negative
22,Virus sekarang nyebarnya melalui media\n,negatif,negative
23,Apalagi ini... Heduftttt\n,netral,neutral
24,Hah ada trend virus lagi\n,negatif,negative
25,lumayan proyek\n,netral,positive
26,Hati hati warga depok\n,netral,positive
27,Nyari balik modal kemaren nyoblos..\n,netral,neutral
28,"Maaf ikut nanya, gmn ya cara ngempesin perut b...",positif,positive
29,SAATNYA DOKTER KEMBALI MERAUP PUNDI PUNDI\n,netral,neutral
30,Bacot\n,netral,neutral
31,Yuhhuuu menyala Abang ku sekolah libur lagi 3t...,netral,neutral
32,Ada vloger yg udh pergi ke china dan dia memba...,netral,positive
33,"Udah ketebak kan arahnya kemana template bgt, ...",positif,neutral
34,"""Wkwk sodara gue yg jadi TKW sana bilang ga ad...",negatif,negative
35,"Di china bawa virus mulu heran, bawa virus kek...",negatif,negative
36,Virus Bisnis yg terstruktur. Abaikan Dan gak u...,netral,negative
37,Percaya? Mendingan gw ajak debat by data aj sa...,netral,positive
38,"Maaf min lg bnyak urussn,gua dulu dah vaksin j...",netral,neutral
39,"Tiap mau puasa kok virus baru, mau larang oran...",negatif,negative
40,Timbang batuk pilek di bilang wabah.. KORUPSI ...,negatif,negative
41,Event apa lagi ini mau dekat ramadhan dan leba...,netral,neutral
42,"Bentar LG lebaran ya,jgn dikasih panggung brit...",netral,positive
43,"banyak fomo nih, jadi rame kan penyakit nya.\n",negatif,negative
44,Yg lagi travelling tiati pulang ke Indo\n,netral,neutral
45,Ini yang bener yang mana beritanya??? Kemenkes...,positif,positive
46,Mana ada di China baik baik aja bos. Gak usah ...,netral,neutral
47,Virus Garuda enak pake ketoprak\n,netral,neutral
48,Yailah bilang aja radang\n,negatif,neutral
49,"kalo disini namanya meriang, dah ada dari dulu\n",netral,neutral
50,"Rakyat indo harus kompak,kita tidak muw di bod...",negatif,negative

Adakah Cyber Bullying yang terjadi di Akun IG Indozone ID? jelas sekali ada karena masih banyak komentar negatif yang ada di kedua metode walaupun dengan Naive Bayes ada di urutan kedua, sedangkan dengan Lexicon ada di urutan pertama

In [105]:
df_['hasil sentimen'].value_counts()

hasil sentimen
netral     27
negatif    20
positif     3
Name: count, dtype: int64

In [104]:
df_['lexicon_sentiment'].value_counts()

lexicon_sentiment
negative    22
neutral     19
positive     9
Name: count, dtype: int64

Dari 2 preview diatas bisa menunjukkan bahwa metode yang berbeda walaupun dengan dataset yang sama bisa memiliki hasil yang berbeda juga

##Kesimpulan

Kesimpulan yang dapat diambil dari penelitian diatas adalah banyaknya data latihan dapat menentukan perbedaan besar hasil dari Sentiment Analysis.

Dengan 400 training data yang saya dapatkan dari hasil googling, kedua Metode pasti Memiliki hasil yang berbeda dan itu tetap tergantung seberapa banyak data training yang dapat kita gunakan untuk melatih metode tersebut.

Dan di Penelitian ini bisa saya katakan bahwa cyberBullying akan tetap ada (walaupun bukan mayoritas tapi tetap bisa memperburuk keadaan) jika kita tidak menanamkan sifat positif pada diri kita. Sebarkan positifitas kita ke orang-orang di sekitar dan terus lakukan itu hingga semua orang dapat lebih memikirkan hal Positif daripada negatif.